### ISSUE TITLE
OuiListItem - Change alignment of left icon

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#1000]
When OuiListItem wraps to two lines, the icon on the left (not the action icons) remain center aligned, which feels visually broken and adds noise to the UI. 

<img width="329" alt="Screenshot 2023-08-29 at 11 18 05 AM" src="https://github.com/opensearch-project/oui/assets/105819041/a686c43f-eca9-46f2-b44c-6078d610316c">

Desired layout is to align with the first line of text 

<img width="390" alt="Screenshot 2023-08-29 at 11 21 53 AM" src="https://github.com/opensearch-project/oui/assets/105819041/9581b709-ca88-45b7-9081-2cf0ac9ad106">

_NOTE_ ignore the different padding between examples. mockup is made with "flush" in mind, prototype does not have flush implemented

**Comment by BSFishy** [comment]
The individual items are flex, which may make it a little bit difficult. In my testing, making it `flex-start` and adding `margin-top: 6px` worked, I think, but that would need to be changed to use `$ouiSize` in the real implementation.
