### ISSUE TITLE
Rename `crossInACircleFilled` to `crossInCircleFilled`

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#1045]
https://opensearch.slack.com/archives/C05389T9LJC/p1695072084427309?thread_ts=1694535707.701519&cid=C05389T9LJC

The files should be renamed to not have the `A` and the icon type should be `crossInCircleFilled` but `crossInACircleFilled` should still point to `crossInCircleFilled` for backwards compatibility

**Comment by kubabal** [comment]
I can take this on
