### ISSUE TITLE
[ISSUE] Documenataion Issue in developer guide

### ISSUE THREAD

**Issue by NishantSinghal19** [opensearch-project/oui#1057]
Developer Guide suggest you to use latest version of Node which is version 20 going so but OUI works with node version 18.5 .

So i can make a just small pr with add a small extra detail about using this version while developing

**Comment by BSFishy** [comment]
Looking at the developer guide, it looks like it just recommends using `nvm` to install whatever is in `.nvmrc`. Is that what you meant?

**Comment by NishantSinghal19** [comment]
Ya but still like can we mention it still there to recommend use that version with NVM use command on that page

**Comment by BSFishy** [comment]
Ah, I see what you're saying. Sure, feel free to make a PR to propose new wording
