### ISSUE TITLE
[BUG] Fix console warnings about 'Query' export

### ISSUE THREAD

**Issue by JohnathonBowers** [opensearch-project/oui#1063]
**Describe the bug**

When I try to run the OUI documentation site, I see a number of warnings in my console regarding a missing export 'Query'.

**To Reproduce**
1. Fork the OUI repo and clone it to your local machine
2. Run `yarn install` and then `yarn start`
3. Visit localhost:8030 on your browser (Chrome, in my case)
4. Right click on browser screen, choose 'Inspect'
5. Click on the 'Console' tab

**Expected behavior**

These warnings should not appear. :)

**Screenshots**

<img width="1030" alt="Screenshot 2023-10-05 at 5 06 46 PM" src="https://github.com/opensearch-project/oui/assets/109883576/1a727832-acf1-4b38-b436-3c03a4764e29">

**Host/Environment (please complete the following information):**
 - OUI Version: 1.22.19
 - OSD Version (if applicable): N/A
 - OS: macOS Ventura 13.5.2
 - Browser and version: Chrome (Version 116.0.5845.187 (Official Build))

**Additional context**

N/A

**Comment by BSFishy** [comment]
This appears to be an issue with (maybe?) Typescript and exporting the `Query`/`Ast` types (the logs in the console that say they're warnings). See https://github.com/opensearch-project/oui/pull/770#discussion_r1199627364

I've been investigating this for a little bit and can't find anything on my end. What Babel outputs (which runs after Typescript) has correct exports, so this is maybe just a bug in Webpack.

This will probably be a matter of changing lines that say

```ts
import { Query } from './query';
```

into

```ts
import { Query } from './query/query';
```

Most likely will need this change in
 * `src/components/search_bar/index.ts`
 * `src/components/search_bar/search_bar.test.tsx`
 * `src/components/search_bar/search_bar.tsx`
 * `src/components/search_bar/search_filters.test.tsx`
 * `src/components/search_bar/search_filters.tsx`

You can see how those files are change in #770 for these changes

**Comment by JohnathonBowers** [comment]
Is it okay to also address the issue with the 'Ast' import as a part of this bug fix, or should I just focus on the 'Query' import?

**Comment by BSFishy** [comment]
> Is it okay to also address the issue with the 'Ast' import as a part of this bug fix, or should I just focus on the 'Query' import?

Yeah definitely. No need in creating multiple PR/issues if they are related :)

**Comment by JohnathonBowers** [comment]
I was able to update the path names like you suggested and get the site to run without warnings. It appears that `./query` was directing to `.query/index` (see screenshot below), so changing the path names to `.query/query` did the trick.

<img width="1025" alt="Screenshot 2023-10-05 at 8 39 05 PM" src="https://github.com/opensearch-project/oui/assets/109883576/a5e15979-dd55-41c5-affc-021e600c6f5c">

The issue with AST was that the original class had been named `_AST` but it was being imported in a couple other files as `AST` (no underscore).

Here is what my console looks like now. Much better!

<img width="1581" alt="Screenshot 2023-10-05 at 8 51 54 PM" src="https://github.com/opensearch-project/oui/assets/109883576/1309c63f-308c-4f5a-8453-222d4f2ace14">

**Comment by AwesomeSauce42** [comment]
Hi, tried to reproduce this error, but my console doesn't show any warnings.
![image](https://github.com/opensearch-project/oui/assets/88332189/62580d50-b578-487e-8238-356c98c1e180)

**Comment by BSFishy** [comment]
> So, I'm not sure what is causing this particular warning. Any thoughts?

Yeah, most likely you'll need to make a separate export in `src/components/search_bar/search_bar.tsx`:

```ts
export { Query } from './query/query';
export { AST as Ast } from './query/ast';
```

**Comment by JohnathonBowers** [comment]
I tried the fix you suggested, but I'm still getting the warning in my browser console:

<img width="535" alt="Screenshot 2023-10-10 at 7 41 37 PM" src="https://github.com/opensearch-project/oui/assets/109883576/52774790-9f5e-4426-8df7-352c1feb6fec">

<img width="1344" alt="Screenshot 2023-10-10 at 7 42 18 PM" src="https://github.com/opensearch-project/oui/assets/109883576/fd4dbcca-6d01-4a2f-8871-f7a2907335d8">

I've done some digging, and, as best I can tell, I think the issue is arising when 'AST' is being exported under an alias. I tried getting rid of the alias in this file and the other files that use it, and the warning disappears from my browser console: 

<img width="588" alt="Screenshot 2023-10-10 at 7 53 25 PM" src="https://github.com/opensearch-project/oui/assets/109883576/e8467825-3722-478b-bbf8-1d4c30b97583">

<img width="1351" alt="Screenshot 2023-10-10 at 7 54 00 PM" src="https://github.com/opensearch-project/oui/assets/109883576/b66416cf-c7c0-4e08-9e9e-280edb5e09c8">

**Comment by joshuarrrr** [comment]
@JohnathonBowers Go ahead with that fix to de-alias `AST`. I still wish we had a better understanding of what's causing the issue, and why it only appeared recently. @AMoo-Miki Is this something you recognize at all from other bundling/building work?

**Comment by JohnathonBowers** [comment]
Sounds good, @joshuarrrr . Is it okay to open up a separate issue for this, or would you prefer that I keep the fix in the same PR as the Query path fix?

**Comment by joshuarrrr** [comment]
separate PR/issue is always welcome

**Comment by AMoo-Miki** [comment]
>  @AMoo-Miki Is this something you recognize at all from other bundling/building work?

@joshuarrrr yes. Something similar came up when upgrading webpack: https://github.com/opensearch-project/oui/pull/770#discussion_r1199627364

**Comment by BSFishy** [comment]
I said this in Slack, but my theory is something along the lines that Webpack has some sort of bug on Mac in v4 and always in v5 that causes this. Potentially some sort of platform-specific optimization in v4, since this only popped up when people started using Mac's to develop. I checked the Babel output for both CJS and ESM for these files, and they seem just fine, even work without any problems with Node. In my mind, that only leaves Webpack as the culprit of this issue.
