### ISSUE TITLE
[BUG] "Guidelines" Documentation Render Blank Page

### ISSUE THREAD

**Issue by Willie-The-Lord** [opensearch-project/oui#1109]
**Describe the bug**

When navigating to the Source Documentation page and clicking on either the "Colors" or "Sass" sections, both render blank pages instead of displaying the relevant documentation.

**To Reproduce**

1. On the side nav, click on either "Colors" or "Sass"
3. Observe that both pages render blank page

**Expected behavior**

Upon clicking on "Colors" or "Sass", users should be able to see the corresponding documentation for these sections instead of a blank page.

**Screenshots**

https://github.com/opensearch-project/oui/assets/65143821/6ab9b421-eeb1-4a55-bad4-46d4c4db3096

**Comment by Willie-The-Lord** [comment]
Currently working on it :)

**Comment by BSFishy** [comment]
For context, this is due to the format of the generated scss-to-js-loader code changing when we migrated to dart-sass

**Comment by Willie-The-Lord** [comment]
I see. Thanks for the info!
