### ISSUE TITLE
(OUI Docs) Docs Site Header

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#111]
These changes are necessary before go live: 

- [x] Remove Figma link/icon
- [x] Remove Codesandbox link/icon
- [x] Remove Cascadia options (Cascadia: Light, Cascadia: Dark) from theme dropdown
- [x] Remove Babelfish (comment out pending further testing and localization strategy) 
- [x] Change logoElastic to logoOpenSearch
- [x] Replace favicon with OpenSearch favicon

**Comment by bandinib-amzn** [comment]
Hi @KrooshalUX 

Thanks for creating this issue. I need more information on 5th task. When you say `Change logoElastic` to `logoOUI`, do you mean that replace the text `logoElastic` with `logoOUI` in code or change below icon in header?
<img width="41" alt="Screen Shot 2022-11-08 at 3 38 39 PM" src="https://user-images.githubusercontent.com/63824432/200699333-5bc7e6b1-6c67-40ea-bad5-7e00156fd31d.png">

**Comment by bandinib-amzn** [comment]
> @bandinib-amzn this is meant to just update the reference away from elastic to oui. This will create a reference to a broken image, I need to commit my logo change which will resolve this.

Thanks @KrooshalUX clarification. So will it be fine to raise a PR which create a reference to a broken image? Should I wait for your logo change and we can work in parallel ?

**Comment by bandinib-amzn** [comment]
Also we have `logoElasticsearch` and `logoElasticStack` in some files. Should we also change those?

**Comment by KrooshalUX** [comment]
@bandinib-amzn :

Re: I can make a commit with a the temporary logo once I land tomorrow, I am away from my computer for the day. 

Re: other logos (including logoTimelion etc) I am changing those as I come across them - I am tracking per page.

**Comment by bandinib-amzn** [comment]
> tomorrow, I am away from my computer for the day.

That would be absolutely fine @KrooshalUX. I am just asking questions here so that I can keep track of those. It can wait till tomorrow.

**Comment by KrooshalUX** [comment]
@AbhishekReddy1127 just a quick update - the find-replace that was done for Elastic to OUI incorrectly prescribed to change `logoElastic` to `logoOUI` when the change should have been to `logoOpensearch`. Updated in the issue description and will update in other issues where `logoOUI` now appears after the early changes that the previous engineering team did a find-replace.

**Comment by KrooshalUX** [comment]
Re-opening: The PR #109 didn't address the last bullet point to remove the Elastic logo.
