### ISSUE TITLE
[BUG] Tree view expanded view

### ISSUE THREAD

**Issue by ps48** [opensearch-project/oui#1118]
**Describe the bug**
The current implementation of tree view expanded node has a limit in height of `100vh`. This is an issue when the children of the a tree node take more then `100vh` of space. The next tree nodes overlap content on UI. In our implementation we use `overflow` property to make the tree view scrollable and removed the max height limit. 

**To Reproduce**
1. Take a sample snippet from https://oui.opensearch.org/1.3/#/navigation/tree-view
2. Load a tree view node with values that take more than 100vh space when expanded 

#### Probable solutions
1. Oui can have a the limit override option as props. 
2. Oui can mention the limit as a note in the website so that users know the limitation. 

For our use-case, removing max-height limit worked:
```
.workbench-tree {
  .euiTreeView__node--expanded {
    max-height: none !important;
  }
}
```

**Screenshots**
![Screenshot 2023-10-27 at 6 12 59 PM](https://github.com/opensearch-project/oui/assets/4348487/de19296d-5353-4d40-867b-986817c36e1f)

**Host/Environment (please complete the following information):**
 - OUI Version: 1.3
 - OSD Version (if applicable): 2.11
 - OS: 2.11
 
**Additional context**

**Comment by keskami** [comment]
ill take this issue
