### ISSUE TITLE
Hover over the filter is not showing text in vertical bar visualization in OpenSearch dashboards

### ISSUE THREAD

**Issue by tejashu7** [opensearch-project/oui#1129]
Description:
Hover over the filter is not showing text in vertical bar visualization in OpenSearch dashboars.

1. Create a vertical dashboard with 2 legends.
2. Click on the legend it will open the color palette and filter options.
3. Hover on the “+” → filter out value which appears after the legend is clicked for color palette filter as shown for Kibana. The hover text over that “+/-” sign is not appearing for OpenSearch-dashboards.

**Expected behavior**
A text descipbing the filter out value should be shown when hovered over the "+" sign.

**OpenSearch Version**
 OpenSearch 2.6.0

**Dashboards Version**
OpenSearch Dashboard version is 2.6.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

Please find the forum link for further details:
https://forum.opensearch.org/t/hover-over-filter-in-vertical-bar-in-opensearch-dashboards-not-showing-text/14124

**Comment by BigSamu** [comment]
@joshuarrrr,

May I take a look at this issue? Feeling is something straightforward or not?

Regards,

Samuel

**Comment by joshuarrrr** [comment]
Yep, @BigSamu , I think this would be a good issue for you to do a little more investigation on. We'll still need Kevin to provide some guidance on the intended behavior, but you can dig into the implementation of the `isIconOnly` prop to see how we might best fix it.

**Comment by kgcreative** [comment]
@joshuarrrr + @BigSamu -- For accessibility (and usability) reasons, if the form element doesn't have a label (which looks like button groups probably wouldn't), then a tooltip (https://oui.opensearch.org/1.3/#/display/tooltip) should display that information. `filter for` and `filter out` make sense here, although a nice to have would be `filter for {key:value}`

**Comment by BigSamu** [comment]
> Yep, @BigSamu , I think this would be a good issue for you to do a little more investigation on. We'll still need Kevin to provide some guidance on the intended behavior, but you can dig into the implementation of the `isIconOnly` prop to see how we might best fix it.

Great! Thanks @joshuarrrr !

> @joshuarrrr + @BigSamu -- For accessibility (and usability) reasons, if the form element doesn't have a label (which looks like button groups probably wouldn't), then a tooltip (https://oui.opensearch.org/1.3/#/display/tooltip) should display that information. `filter for` and `filter out` make sense here, although a nice to have would be `filter for {key:value}`

Perfect, thanks @kgcreative, I will start working on this issue next week. Now much more familiar with the whole OUI base code.

**Comment by BigSamu** [comment]
@joshuarrrr @kgcreative 

It took me a while to understand the whole implementation of both codes (osd and oui) to understand the problem. But at last, here I have a simple solution.

In OUI library, in `button_content.tsx` file, we can have the following for the return of the component:

```jsx
 return (
    <span {...contentProps} className={contentClassNames}>
      <span {...textProps} className="" >{buttonIcon} </span>
      <span {...textProps}>{children}</span>
    </span>
  );
```

Instead of,

```jsx
return (
    <span {...contentProps} className={contentClassNames}>
      {buttonIcon}
      <span {...textProps}>{children}</span>
    </span>
  );
``` 

The dictionary `textProps` for the case of a iconOnly button contains the following:

```js
{className: 'ouiButton__text ouiButtonGroupButton__textShift', data-text: 'Option three', title: 'Option three', ref: ƒ}
```

By adding, `className=""` after `{...textProps}` we override the initial definition of `className` coming in `textProps`. This simple solution works allowing us to visualize the tooltip. Of course, I feel it is not quite elegant, and maybe we should move the HTML attributes `data-text` and `title` to the `contentProps`

Below is a screenshot applying this small change in the code of the OUI documentation.

![image](https://github.com/opensearch-project/oui/assets/28614451/56aba9d4-03f5-4abe-9bce-1690801e34a4)

Looking forward to your comments.

Samuel

**Comment by joshuarrrr** [comment]
@BigSamu I think that makes sense - we may need to validate that duplicating the props don't cause any side effects, but go ahead and open a PR, and we can go from there.

**Comment by BigSamu** [comment]
Hi @joshuarrrr @kgcreative, PR #1160 is already open for your review. Looking forward to your comments.

**Comment by joshuarrrr** [comment]
completed via #1160. For follow-up, see https://github.com/opensearch-project/oui/issues/1207

**Comment by BigSamu** [comment]
I will take #1207 to continue enhancing this feature
