### ISSUE TITLE
[OSCI] Plugin Babel Dependencies Deprecated (Proposal-Class-Properties and Proposal-Object-Rest-Spread)

### ISSUE THREAD

**Issue by BigSamu** [opensearch-project/oui#1130]
**Is your feature request related to a problem? Please describe.**

Dev dependencies [@babel/plugin-proposal-class-properties](https://www.npmjs.com/package/@babel/plugin-proposal-class-properties) and [@babel/plugin-proposal-object-rest-spread](https://www.npmjs.com/package/@babel/plugin-proposal-object-rest-spread) are deprecated.

**Describe the solution you'd like**

Dependencies need to be updated for the following ones:
-  [babel-plugin-transform-class-properties](https://www.npmjs.com/package/babel-plugin-transform-class-properties)
 - [babel-plugin-transform-object-rest-spread](https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread)

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by JohnathonBowers** [comment]
Could I be assigned this issue? Thanks!
