### ISSUE TITLE
(OUI Component Refresh) Add prop to set OuiIcon type=search true or false

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#130]

**Comment by BSFishy** [comment]
@KrooshalUX Should the search icon replace the arrow icon? If not, then this is down to the user of this component.

The combo box input already provides an `icon` prop (which is the arrow on the right side):
https://github.com/opensearch-project/oui/blob/ab3ba28e4969f0685747665620d97aae7c1dbf4a/src/components/combo_box/combo_box_input/combo_box_input.tsx#L262-L272

The user of the component could do something like this:

**Comment by KrooshalUX** [comment]
It would be to the left, not replacing the arrow: 

<img width="452" alt="Screen Shot 2022-11-21 at 3 14 17 PM" src="https://user-images.githubusercontent.com/105819041/203176925-a54d1bda-4a9d-487d-8944-1811dab95324.png">

I would want to limit it to just search icon, vs any configurable icon/glyph in the set.

**Comment by KrooshalUX** [comment]
Sorry this title was auto generated and I will update when not out of pocket - it’s a sub to the meta that is listed as a reference in this issue.

On Nov 22, 2022, at 6:29 PM, Ashwin P Chandran ***@***.***> wrote:

﻿

Can we rename the issue title or add some context to the issue description? I'm not sure which Oui component we want to alter here. Also whats the purpose of this alteration. From what i can gather I'm assuming that we want to add a search icon to the combo box. This should already be possible, or am i missing something?
