### ISSUE TITLE
[BUG] Class name prop is not passed down for OuiSearchBar component

### ISSUE THREAD

**Issue by ps48** [opensearch-project/oui#1343]
**Describe the bug**

The OuiSearchBar component extends commonprops which contains className and data-test-subj. These are necessary and are used by many plugins for testing and styling. The issue is even though these props are taken in by the OuiSearchBar, they aren't passed down or used in the rendered JSX components. 

**To Reproduce**
1. Use OuiSearchBar component to a render search bar in OSD/ any OSD plugin
2. Add a class name prop example: 
``` 
     <EuiSearchBar
        className="myclass"
        box={{
          placeholder: 'Search to filter Available Metrics',
          incremental: true,
        }}
        defaultQuery={''}
        query={searchText}
        onChange={onChange}
      />
```
3. Go to browser inspect the search bar component to check class. 
4. See the class name isn't propogated
<img width="952" alt="Screenshot 2024-08-14 at 1 42 27 PM" src="https://github.com/user-attachments/assets/30b24bff-6736-4d49-92fc-9289471f3eb4">

**Expected behavior**
The class names should be propagated to the child components

**Host/Environment (please complete the following information):**
 - OUI Version: 1.9.0
 - OSD Version (if applicable): 3.0.0
 - OS: Mac OS
 - Browser and version Firefox

**Additional context**

**Comment by AMoo-Miki** [comment]
Will consume `className` on the wrapper. The `box` prop hands down everything within it to the underlying `OuiSearchBox`. Will deprecate `aria-label` and `data-test-subj` which have never been used.
