### ISSUE TITLE
Non-yarn Installation Instructions

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/oui#139]
**Is your feature request related to a problem? Please describe.**

I'd like to implement OUI on our statically generated jekyll  site. So far the only 'installation' instructions are to use yarn. 

**Describe the solution you'd like**

I see two solutions. 

1. Someone creates a yarn file for us that we can place at the root of our website-project github repo so that yarn can be used to install it in an appropriate location or 
2. A non-yarn tutorial / build process for grabbing all of the assets and styles so that we can include them from our site layouts 'the old fashioned way'

**Describe alternatives you've considered**

Rebuilding project-website with Gatsby or some other kind of react ready static site generator. 

**Additional context**

I hope this doesn't indicate too much ignorance on my part. These fancy-schmancy react component libraries are new to me. I'm slowly getting up to speed. 

Thanks!

**Comment by BSFishy** [comment]
One thing that we could do is upload `oui.min.js` as well as any `oui_theme[...].min.css` as artifacts when we create Github releases. It's not ideal, as updating to newer OUI versions would be manual, but it would be an option for cases like this

**Comment by nateynateynate** [comment]
This might have been my own doing in regards to yarn not working - apparently Ubuntu selects 'cmdtest' when you tell it to install yarn. After getting the `actual` yarn installed, I was able to `yarn build`

I'll leave this open, as it might be good fodder for adding a document on describing the build process.

**Comment by BSFishy** [comment]
Alternatively, other libraries like Bootstrap usually provide a CDN link using services like [jsDelivr](https://www.jsdelivr.com/). That one can grab files directly from the published NPM package, so it would be minimal setup on our end.

One thing that should be up for discussion, though, is if this should be within the scope of the project, being a React library and targeted at being used in a Webpack-style bundling system.

**Comment by nateynateynate** [comment]
> One thing that should be up for discussion, though, is if this should be within the scope of the project, being a React library and targeted at being used in a Webpack-style bundling system.

Now that I've learned a thing or two about a thing or two, I couldn't imagine going through the compilation process any other way other than using yarn. I'd still like to be able to use something like jsDelivr so that when things are updated and changed that they reflect on our website too.
