### ISSUE TITLE
Use dart-sass instead of node-sass

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#160]
**Is your feature request related to a problem? Please describe.**

`node-sass` is a deprecated module that is not very well maintained.

**Describe the solution you'd like**

`node-sass` should be replaced with `dart-sass`. `dart-sass` (or just [plain `sass` on npm](https://www.npmjs.com/package/sass)) is a newer pure Javascript implementation of Sass that is much better maintained and will support us better in the future. [Dashboards has already made this change](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2054).

**Comment by BSFishy** [comment]
This may need to be something we take care of when we revamp the theming system. Currently, we use [`sass-vars-to-js-loader](https://www.npmjs.com/package/sass-vars-to-js-loader), which has a dependency on `node-sass`. So we would either need to replace that (which it doesn't look like there is a good 1:1 replacement as of now) or wait until we don't need it anymore.

**Comment by ashwin-pc** [comment]
A similar migration was mad in OSD for reference. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2054

**Comment by BSFishy** [comment]
Finished in #1001
