### ISSUE TITLE
Update bug report issue template

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#182]
Currently, the bug report issue template is copied over from OSD and contains some sections that don't apply to OUI. The template should be updated to provide a simpler experience for newcomers.

Action items:
 - [ ] Remove `OpenSearch Version` section
 - [ ] Remove `Dashboards Version` section
 - [ ] Remove `Plugins` section
 - [ ] Add `OUI or OSD version` to `Host/Environment` section

Current template for reference: https://github.com/opensearch-project/oui/blob/dd4d1ab2938a3bacd9f0470421fde568eb3e2b9c/.github/ISSUE_TEMPLATE/bug_template.md

**Comment by KrooshalUX** [comment]
I would propose that we leave the OSD versions in the bug report template, as it may help us diagnose which version of OUI is being referenced in case the reporter cannot identify it themselves. I don't expect that OSD will always have the latest-and-greatest version of OUI once we move away from aliasing.

**Comment by BSFishy** [comment]
I don't love the idea of leaving in OSD version if we're expecting customers outside of OSD. I feel like it might make the process of making a bug report monotonous for customers outside of OSD if they need to delete that section each time or write N/a. Maybe we could make it `OUI/OSD version` instead of just `OUI version`?

**Comment by curq** [comment]
Hi @BSFishy @KrooshalUX, I updated the template, could you please check it? Thanks!

**Comment by joshuarrrr** [comment]
fixed via #764
