### ISSUE TITLE
[PROPOSAL] Enable github pages to showcase components

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/oui#20]
Add github pages and add examples of the components, how to use them and a style guide. Then replace the living style guide link with the github pages link.

**Comment by ashwin-pc** [comment]
Do we still need this if we have oui.opensearch.org?

**Comment by kaddy645** [comment]
style guide : is it for the end user or for UX team to play around?

**Comment by ashwin-pc** [comment]
Yep

**Comment by AMoo-Miki** [comment]
The `oui.opensearch.org` should contain the consumer documentation.

**Comment by BSFishy** [comment]
For future reference, Storybooks can be built into a static site: https://storybook.js.org/docs/react/sharing/publish-storybook

**Comment by AMoo-Miki** [comment]
This was discussed offline and for the kind of things we would like to do, such as but not limited to url-rewrite, GitHub Pages wouldn't be a suitable option. Also, `oui.opensearch.org` is now on its way.
