### ISSUE TITLE
(OUI Docs) Key pad menu

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#200]
Section: Beta item

- [x] Change header  "Beta item" to "Experimental item"
- [x] Change "If the item links to a module that is not GA (beta, lab, etc)" to "If the item links to a module that is not GA (experimental, lab, etc)"
Update reference from Beta badge to Experiemental badge:
- [ ] `betaBadgeLabel` to `experimentalBadgeLabel`
- [ ] `betaBadgeTooltipContent` to `experimentalBadgeTooltipContent`
- [ ] `EuiBetaBadge` to `OuiExperimentalBadge`
- [x] In the visual example, replace the "B" with the lab icon to reflect the guidance for Experimental badge

- [x] Remove "Supplying just a label will only show the first letter in the badge and supply the full label to the tooltip." as it is no longer in-line with Experimental badge guidance. 
- [x] Change "You can also pass an iconType to replace the letter only badge and the label will still become the title." to "You can pass an iconType and the label will become the title."

**Comment by BSFishy** [comment]
For the beta badge ones, it might not make sense right this moment, because the experimental badge hasn't been implemented yet. #161 for tracking

**Comment by KrooshalUX** [comment]
@BSFishy yes - I am not sure what we use to call out dependencies and blocking issues until they are do-able. I would consider this one blocked until `OuiExperimentalBadge` is available.
