### ISSUE TITLE
[SPIKE] Understand under the hood functionalities

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/oui#21]
Research into this repo

* What do we need to work on
* Update themeing? Existing bugs
* Icons? Branding
* https://github.com/opensearch-project/oui/issues/22
* Research into how accurate the current wikis are.

Requirements:
* Need a roadmap
* Get user interaction information (how is this information collected)

**Comment by kavilla** [comment]
@kaddy645 @bandinib-amzn @AMoo-Miki @opensearch-project/opensearch-ux

**Comment by KrooshalUX** [comment]
Working version of the roadmap for theming here: https://quip-amazon.com/pacoA2FVtJwg/Theming-Roadmap-Draft

**Comment by KrooshalUX** [comment]
This issue is out of date, and no longer needed. Closing.
