### ISSUE TITLE
Auto-delete old caches

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#211]
Utilize [the workflow in this guide](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries) to create a workflow that automatically deletes caches for pull requests that have been merged or closed. Once a pull request has been merged or closed, it has no use for the cache anymore, so the cache can be deleted.

**Comment by AMoo-Miki** [comment]
Don't caches expire on their own?

**Comment by BSFishy** [comment]
> How does it help deleting them sooner?

According to Github directly:

> For example, a repository could have many new pull requests opened, each with their own caches that are restricted to that branch. These caches could take up the majority of the cache storage for that repository. Once a repository has reached its maximum cache storage, the cache eviction policy will create space by deleting the oldest caches in the repository. In order to prevent cache thrashing when this happens, you can set up workflows to delete caches on a faster cadence than the cache eviction policy will.
