### ISSUE TITLE
(OUI Docs) Side nav

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#215]
Section: Complex side nav

- [ ] Replace content in this section with the following `OuiTreeView` containing (list items represent nested content within the tree, no icons in the major sections, we will add these back when Icons have been re-created for OUI):

**OpenSearch**
Discover
Dashboard
Visualize
Stack Management
- Index Patterns
- Data Sources
- Advanced Settings
      - `<OuiIcon type="gear" />` General
      - `<OuiIcon type="accessibility" />` Accessibility
      - `<OuiIcon type="discoverApp" />` Discover
      -`<OuiIcon type="bell" />` Notifications
      - `<OuiIcon type="search" />` Search
      - `<OuiIcon type="timeline" />` Timeline
      - `<OuiIcon type="visArea" />` Visualization
- Saved Objects
 
**Observability**
Application analytics
Trace analytics
Event analytics
Metrics analytics
Operational panels
Notebooks 

Section: Nested item options
- [ ] Remove Icon next to "kibana"
- [ ] Change "Kibana" to OpenSearch Dashboards

**Comment by AbhishekReddy1127** [comment]
Fixed #260
