### ISSUE TITLE
[UX/OUI] Move global styles header breadcrumb to OUI

### ISSUE THREAD

**Issue by kaddy645** [opensearch-project/oui#22]
The breadcrumb restyling completed in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1954 should be migrated here to become the new default OUI breadcrumb styles. Because we'll have full control of the component here, we'll likely want to refactor the breadcrumbs entirely, not just apply the patched styles.

After implemented then create issue in OpenSearch Dashboards to utilize the new breadcrumbs

Requirements:
* Styling in OUI for the new breadcrumbs
* New property to switch between the two
* Documentation updated (?)

**Comment by kavilla** [comment]
@KrooshalUX will add more context, for example sizing.

**Comment by kavilla** [comment]
@KrooshalUX could we get the finalized colors? Thank you!!

**Comment by KrooshalUX** [comment]
@kavilla the colors are finalized. Can you specify what you think may be missing ?

**Comment by KrooshalUX** [comment]
The design adjustment that is remaining is to make the left padding of the first breadcrumb 8px vs 12px which it is currently implemented as. Previously with EUI we were locked in to using even padding on r&l. With moving to OUI we should now be able to customize those values.

**Comment by ashwin-pc** [comment]
@BSFishy what are some of the approaches you have tried and why did you decide against them? `clip-path` is my preferred approach here.
