### ISSUE TITLE
Investigate searching and filtering a list of items by metadata not displayed in the list

### ISSUE THREAD

**Issue by lauralexis** [opensearch-project/oui#227]
Is it feasible, using our search, filter, and table components, to search and filter a list of items by metadata that is not displayed in the list?

**Let me describe my use case:**

The model registry has many models. Each model can have many versions. I want to be able to search and filter the model registry, which contains a list of models, for metadata that is related to a model version.

For example, I want to search the model registry for models that contain versions that have the tag “Task: Image Classification”, or the metric “Accuracy > 0.99”.

Figure 1: A video of some of the desired behavior, showing a model registry where the list view is filtered by metadata not displayed on each list item.
https://user-images.githubusercontent.com/16546056/212114018-23eee5eb-3e2d-477b-99d4-31431a1a58a7.mov

Figure 2: Early mockup of model registry table view, showing a list of models, each containing multiple versions.
<img width="1028" alt="Screen Shot 2023-01-12 at 10 47 51 AM" src="https://user-images.githubusercontent.com/16546056/212113735-45be6eab-fe7e-413b-8d21-8046059b7bc0.png">

Figure 3: Model registry object relationships and metadata.
<img width="319" alt="Screen Shot 2023-01-12 at 10 45 41 AM" src="https://user-images.githubusercontent.com/16546056/212113200-89c480b0-01f9-4d6d-8282-bc30e82581ff.png">

**Comment by KrooshalUX** [comment]
Currently no action item required from OUI, I believe that the engineering partners @lauralexis  was working with have proven out that the metadata was searchable.
