### ISSUE TITLE
(OUI Docs) Table

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#234]
- [ ] Remove all GitHub links and replace with relative link to OUI documentation https://oui.opensearch.org/latest/

**Comment by ananzh** [comment]
Hey @KrooshalUX 

For this issue, do you mean in this folder [src-docs/src/views/tables](https://github.com/opensearch-project/oui/tree/main/src-docs/src/views/tables) check the link to elastic (eg `href="http://www.elastic.co"` ) then replace it with `href="https://opensearch.org/docs/latest/"`?

**Comment by KrooshalUX** [comment]
@ananzh  it would be oui.opensearch.org/latest/
