### ISSUE TITLE
(OUI Docs) In-memory tables

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#238]
- [x] Remove GitHub column from all tables

**Comment by BSFishy** [comment]
Short term, we could remove them, but I think it might also be useful for implementors to see an example with links in the cells. We could create a follow-up issue for that, though.

**Comment by KrooshalUX** [comment]
@BSFishy  since links are present in other examples of Basic Table, we will move forward with removing the github column in order to release the docs site.
