### ISSUE TITLE
(OUI Docs Site) Homepage

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#255]
- [ ] Remove graphic 
<img width="477" alt="Screen Shot 2023-02-21 at 2 34 58 PM" src="https://user-images.githubusercontent.com/105819041/220474271-e6ba526f-a174-42c1-aa89-aadf1e6210bf.png">

- [ ] Remove entire card for "Charts" 
<img width="265" alt="Screen Shot 2023-02-21 at 2 35 31 PM" src="https://user-images.githubusercontent.com/105819041/220474365-c496502e-b860-47ae-b0e2-63a0e8086e78.png">

- [ ] Change logoElastic to logoOpenSearch
<img width="432" alt="Screen Shot 2023-02-21 at 2 36 06 PM" src="https://user-images.githubusercontent.com/105819041/220474457-963553bd-9eab-4c34-9ab1-f441aac1b427.png">

**Comment by ananzh** [comment]
Abby will do the third one `Change logoElastic to logoOpenSearch` in [#248](https://github.com/opensearch-project/oui/issues/248)
