### ISSUE TITLE
Create component OuiLoadingDashboards

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#265]
This component is intended to replace the deprecated OuiLoadingElastic component.

Use the custom component that is created for dashboards - original issue found here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/387

- [x] Create Component
- [x] [Add component details to OUI Docs](https://github.com/opensearch-project/oui/issues/267)

**Comment by ashwin-pc** [comment]
The loader can be found here https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.6/src/core/server/rendering/views/template.tsx#L68-L95

**Comment by SergeyMyssak** [comment]
> The loader can be found here https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.6/src/core/server/rendering/views/template.tsx#L68-L95

Hello @ashwin-pc, thank you for the information provided. I am going to work on this issue

**Comment by joshuarrrr** [comment]
completed via https://github.com/opensearch-project/oui/pull/597
