### ISSUE TITLE
(OUI Docs) Toast

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#274]
Tab: Examples 
Section: Danger

- [ ] Change " Error: expected _scroll_id in the folling Elasticsearch response: {"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"skipped":0,"failed":0},"hits":{"total":0,"max_score":0,"hits":[]}}" to 
"Error: expected _scroll_id in the following response: {"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"skipped":0,"failed":0},"hits":{"total":0,"max_score":0,"hits":[]}}"

Tab: Guidelines
Section: Top of page

- [ ] Change "Search failed. Check your Elasticsearch connection." to "Search failed. Check your connection to the cluster."

**Comment by BSFishy** [comment]
Should there be a space between expected and `_scroll_id` in the Danger section change? I.e. `expected _scroll_id` instead of `expected_scroll_id`?

**Comment by KrooshalUX** [comment]
@BSFishy  I am not 100% sure - as I copied this directly from the forked docs site - there were other errors in that blurb so perhaps? I will leave that up to you to make the call if its incorrect from a syntax perspective. 

Here is where I pulled it from, where the space is present: 
<img width="339" alt="Screen Shot 2023-02-15 at 7 33 20 PM" src="https://user-images.githubusercontent.com/105819041/219261668-dedc8306-e51b-4a92-8050-38d48de52f95.png">

**Comment by BSFishy** [comment]
Based on that, it looks like it was just copy pasted weird or something. I think it should be `Error: expected _scroll_id in the following response: {"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"skipped":0,"failed":0},"hits":{"total":0,"max_score":0,"hits":[]}}`
