### ISSUE TITLE
(OUI Docs) Unable to view Tour component props because Tour UI remains in view

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#277]
When viewing the Tour page content, on the first section (Step options), click "props". The tour pop-overs do not dismiss in this view, so the user is unable to properly read or interact with the props UI. 

<img width="1180" alt="Screen Shot 2023-02-05 at 9 25 59 PM" src="https://user-images.githubusercontent.com/105819041/216890518-d7697926-0645-4a7d-a61c-813677551dfd.png">

**Comment by abbyhu2000** [comment]
Close this issue after investigation. The original problem seems to be a local issue. The tour pop over can be closed by clicking `Close tour`, and won't block the Tour component props.
