### ISSUE TITLE
(OUI Docs) Remove Elastic Charts pages

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#286]
- [x] Identify if there are any interlinks within the OUI docs site that point to the following pages, and repsond in a comment with page that the link originated from, tag @KrooshalUX  before proceeding. 

Remove the following pages from the documentation:

- [ ] Creating charts
- [ ] Sizing
- [ ] Time series
- [ ] Categorical
- [ ] Part to whole comparisons

**Comment by BSFishy** [comment]
Interlinks to charts:
 - `Color palettes` under `Recommended quantitative palettes`

Other links related to Elastic charts:
 - Homepage Charts link
 - (misc links under Elastic Charts that will be removed)

@KrooshalUX

**Comment by KrooshalUX** [comment]
@BSFishy  perfect, thanks. I made an update to the related issues for color palettes and homepage. We can proceed with the rest of this issue of removing the pages. Thanks!
