### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/oui#305]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by gaiksaya** [comment]
Please onboard to 2PR approval process after CODEOWNER's file is updated.
Details: https://github.com/opensearch-project/opensearch-build/issues/3111
Sample PR: https://github.com/opensearch-project/opensearch-java/pull/383

**Comment by bbarani** [comment]
The permissions are still not correct. I still see a team with maintain access. There should be no other team added to the repo except for admin and triage team. Everyone else need to be added as individual user.

**Comment by ananzh** [comment]
Hi @bbarani, @BSFishy will work with build team on-call to update permissions.

**Comment by ananzh** [comment]
We have updated CODEOWNER and MAINTAINERS.
Also have @gaiksaya updated the permissions.
Close this issue.
