### ISSUE TITLE
(OUI Icons) Create icon for Polygon Draw

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#309]
Tool allows a user to drop a series of points on a map that will then result in a closed form - all connected with straight lines. Since it is not a prescribed shape (rectangle, pentagon, hexagon, etc) , avoid using perfect geometry. 

This is not a free-flowing interaction. 

Icon inspiration: 
<img width="193" alt="Screen Shot 2022-10-12 at 5 32 53 PM" src="https://user-images.githubusercontent.com/105819041/195472270-c06becc5-cc8f-4963-925d-54ebbc426972.png">
<img width="217" alt="Screen Shot 2022-10-12 at 5 33 06 PM" src="https://user-images.githubusercontent.com/105819041/195472271-552c96a7-97b9-4510-860e-0a71578a6293.png">

**Comment by canascar** [comment]
C urrently WIP on for the Maps Geo Spacial tools.

<img width="508" alt="Screen Shot 2023-02-21 at 9 13 54 AM" src="https://user-images.githubusercontent.com/111922174/220414085-1e1da710-0c77-4a79-9a66-8ec5adbaa9fb.png">
