### ISSUE TITLE
(OUI Icons) Create icon for Freehand Draw

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#310]
Icon represents a tool for freehand drawing any shape to highlight data points on a map. 

This is a more of a flowing gestural interaction than drawing a polygon on the map, which is a series of dropped points and straight lines.

If utilizing a pen or pencil within the icon, be sure to differentiate it from "edit" pencil already within library 

Icon inspiration: 
<img width="28" alt="Screen Shot 2022-10-12 at 5 26 25 PM" src="https://user-images.githubusercontent.com/105819041/195471705-2f961f73-f8a8-48a8-8a2f-57797fe82893.png">

<img width="211" alt="Screen Shot 2022-10-12 at 5 30 08 PM" src="https://user-images.githubusercontent.com/105819041/195472000-bdc5a78e-0d41-489c-8fef-a1a8541e0dcf.png">

**Comment by canascar** [comment]
Currently WIP on for the Maps Geo Spacial tools.
<img width="421" alt="Screen Shot 2023-02-21 at 9 12 05 AM" src="https://user-images.githubusercontent.com/111922174/220413709-9a6af71d-155c-4d48-ba2e-43e08d584d71.png">

**Comment by canascar** [comment]
Is Freehand draw a tool we are introducing? Currently it seems like it's Bounding box, Radial distance, and Polygon draw tools. I can add this in though for future use.

**Comment by KrooshalUX** [comment]
@canascar  this was originally requested by the UX designer that worked on maps previous to your onboarding. Can you validate that this is no longer needed?

**Comment by KrooshalUX** [comment]
Ok, given that context, closing as not planned. Thanks @canascar  for investigating!
