### ISSUE TITLE
[Bug] OuiCopy component causing issues in Safari

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#314]
Summary: 
`OuiCopy` utilizes deprecated command which is causing customer issues in Safari. Please review the following issues to determine next steps and update this issue description as needed.

More details as per @kavilla on issue #1716 in OSD repo:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1716#issuecomment-1158644693

Note: Did not use bug template because bug is accurately described across two issues in OSD: 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/689
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1716

**Comment by AMoo-Miki** [comment]
This works just fine on https://oui.opensearch.org/1.0/#/utilities/copy using Safari. I will check OSD to see if something else could be breaking this.

**Comment by AMoo-Miki** [comment]
The issue occurs as a result of interference from securityDashboards and has nothing to do with OUI or OSD.
