### ISSUE TITLE
Update Writing section of OIU page

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/oui#318]
**Is your feature request related to a problem? Please describe.**

We need to replace the contents in the [Writing section of the OIU page](https://oui.1291fa08092a4a2dfd6d43f11d7bbcf3f22bf569.opensearch.org/latest/#/guidelines/writing) with OpenSearch content.

**Describe the solution you'd like**

The content to include is here: https://github.com/opensearch-project/documentation-website/blob/main/STYLE_GUIDE.md#ui-text

**Describe alternatives you've considered**

This will ensure developers are following OpenSearch guidance.

**Additional context**

**Comment by KrooshalUX** [comment]
@hdhalter - This page will be discontinued on the OUI site, and a new page will be created in OSDS/ OpenSearch Design System documentation site. The reason for this is that the writing guidelines apply to our properties but not necessarily the component libraries which may be used by anyone outside of OSD. 

I am going to close this as a wont-fix and when we have the new repo for the OSDS project, there will be an issue that exists there for the writing guidelines page.
