### ISSUE TITLE
[SPIKE] Research in migrating to new breadcrumbs styling

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/oui#33]
Move the original styling to OUI project.

This will be used as a starting point to make OUI component to make it easier for developers to use via configuration.

Requirements:
* Provide context on this issue for those overrides
* Provide context on any gaps on setting up

**Comment by kaddy645** [comment]
**Goal: Allow developers to toggle between old vs new breadcrumb styles**

- With all the existing props, OuiHeaderbreadcrumb component will accept new prop called "**enableBreadcrumbNewTheme**"  (prop name is temporary)  && **value can be : true or false**
- It will be false by default , making it true will allow developers to see new global breadcrumbs styles.
- Under the hood we will be checking the value of **enableBreadcrumbNewTheme** prop and accordingly different css and classnames will be applied
-  new style will be part of **oui-cascadia theme**
- Usage : ` <OuiHeaderBreadcrumbs enableBreadcrumbNewTheme = {true}` - once the new OuiHeaderBreadcrumbs are ready, we will be moving css from OSD
- new Breadcrumb style :
<img width="1005" alt="Screen Shot 2022-07-19 at 8 19 30 PM" src="https://user-images.githubusercontent.com/105819041/179889170-5159550c-ea35-46be-b075-de65c01ab615.png">


**What to retain:**
- Retain current truncation rules for breadcrumb titles
- Retain current breadcrumb step truncation logic
- Retain typography treatment

**What to update:**
- Remove auto generated “/” characters between breadcrumb steps
- Introduce background shapes with the following details: 
  - Colors:
     - Active / Current Breadcrumb Step 
     - Inactive / Previous Step
   - Shape:
      - Global:
         - Corner Radius: 2px
         - Spacing: Steps within breadcrumb appear to have a gap and never intersect

**Comment by kaddy645** [comment]
Update: https://github.com/opensearch-project/oui/issues/44
we are going to create copy of current theme (light/ dark flavors) and called it as beta (light/dark)

Beta theme will have everything same that our current theme has. We will start making changes to Beta theme and OUI 2.0 (Jan 2023) will have beta as  a default theme.

At the moment we have OUI 1.x so will be keeping both the current and beta themes (light / dark flavors) and current theme (non beta) will be default.

Breadcrumbs and it’s colors / styles will be part of beta theme. (OUI 2.0)

Right now we have two branches 1.x and main and while working on beta theme , We will be making changes to main & 1.x will be as it is.

In future if someone is using OUI 1.x package they can use older styles (non beta ) current theme.

But if someone is using OUI 2.0 they will get new beta theme by default.

Taking about theme folder structure we will have 4 files for OUI 1.x

Current light scss
Current dark scss
Beta light scss
Beta dark scss

For OUI 2.0

Beta light scss
Beta dark scss.

**Comment by ashwin-pc** [comment]
I would just skip the OUI 1.0 step. Wen we move to OUI 2.0 we can replace the existing breadcrumb with the hot-fix to the new breadcrumb. it will simplify the migration. Why are we shooting ourselves in the foot twice?

**Comment by kaddy645** [comment]
> I would just skip the OUI 1.0 step. Wen we move to OUI 2.0 we can replace the existing breadcrumb with the hot-fix to the new breadcrumb. it will simplify the migration. Why are we shooting ourselves in the foot twice?

Yes, above comments are quite old :)

**Comment by BSFishy** [comment]
Decided to use an approach like what is [shown in this JSFiddle](http://jsfiddle.net/z4m1r8jp/). Basically, add an extra element wrapper that skews and adds a background, and have the original element counter-skew for text.

Will completely remove old styles
