### ISSUE TITLE
[BUG] yarn lint is failing

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/oui#41]
**Describe the bug**
```yarn lint``` is failing with following error:

```
$ yarn lint
yarn run v1.22.19
$ yarn tsc --noEmit && yarn lint-es && yarn lint-sass
$ /home/ubuntu/OSD/oui/node_modules/.bin/tsc --noEmit
$ eslint --cache "{src,src-docs}/**/*.{ts,tsx,js}" --max-warnings 0

/home/ubuntu/OSD/oui/src/components/icon/icon.test.tsx
  34:21  error  Unable to resolve path to module 'cheerio'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

Because of failed ```yarn-lint```, I'm not able to commit the changes.

**To Reproduce**
Run ```yarn lint```

**Expected behavior**
```yarn lint``` should be successful.

**OpenSearch Version**
N/A

**Dashboards Version**
N/A

**Plugins**

N/A

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by AMoo-Miki** [comment]
Check Cheerio:
* `rc.7` and `rc.8` have issues with the folder structure in the release packages.
* `rc.6` causes a [single test](https://github.com/opensearch-project/oui/blob/main/src/components/datagrid/data_grid.test.tsx#L597) to fail by not matching the snapshot where the `top` values are off by 100px.
* `rc.5` passes all the tests and tolerates the overridden nested dependencies.
