### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/oui#45]
There are many ```dependencies```, ```devDependencies``` and ```resolutions``` that either very old or no longer relevant/necessary. We need to attempt to bump up the version of dependencies and remove as many manual resolutions as possible to clean up our dependencies.

This will be a parent issue to track the different tasks while updating or removing dependencies and resolutions.

### Task List
- Remove ```start-server-and-test``` devDependencies https://github.com/opensearch-project/oui/issues/46
- CVE- Bump nested dependencies  https://github.com/opensearch-project/oui/issues/49

**Comment by kavilla** [comment]
[Planning]

@bandinib-amzn can you followup on this issue? Should it be closed.

**Comment by bandinib-amzn** [comment]
We are using `start-server-and-test` devDependencies for [automated accessibility testing](https://github.com/opensearch-project/oui/blob/321ee0736d3501134c4a4620bd10a78fc68c0a52/wiki/automated-accessibility-testing.md). Therefore not planning to remove it.

For CVEs, all the necessary packages are updated

Issues :
https://github.com/opensearch-project/oui/pull/50
https://github.com/opensearch-project/oui/pull/55
