### ISSUE TITLE
Support rendering the Drag and Drop visualization type selector using a component from OUI

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/oui#52]
**Is your feature request related to a problem? Please describe.**

No component can easily support this mock for the Visualization chart selector for Drag and Drop

![](https://user-images.githubusercontent.com/93013804/179582005-54c8d8fb-c77a-4c51-b62a-5f266cd0e5be.png)

**Describe the solution you'd like**

Modify `SuperSelect` to allow such a view to be rendered and used.

**Describe alternatives you've considered**

- Create a new component
- Modify the button component to support an `asSelect` prop that styles it as a Select button so that it can be used a custom select
- Modify the `Popover` component to style the button as a select

**Additional context**

**Comment by KrooshalUX** [comment]
@btzeng  lets revisit this before your time off to come up with a solution that either uses existing OUI component or consider creating a new component based on what has been developed already. I can see OUISuperSelect potentially utilizing cards & logos but we need to further explore.

**Comment by btzeng** [comment]
@KrooshalUX  The design in this issue was created a while ago, the updated design is using a dropdown list to display all vis types in this flat list. 
<img width="252" alt="chart select" src="https://user-images.githubusercontent.com/93013804/200375932-015761fa-0a4b-4c87-ad84-4b9ab0bead0c.png">

**Comment by BSFishy** [comment]
@ashwin-pc With what @btzeng mentioned, can this be closed?
