### ISSUE TITLE
Remove charts theme code

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#531]
OUI doesn't provide any sort of charting. As a carryover from EUI, we still have a [`src/themes/charts`](https://github.com/opensearch-project/oui/tree/a657d1f16be5953b89b38fc085221f0b39fc18f8/src/themes/charts) folder. That can be deleted assuming that it's not being used anywhere.

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue.

**Comment by BSFishy** [comment]
Sure, I'll assign it to you. Please don't hesitate to reach out if you have any questions!

**Comment by SergeyMyssak** [comment]
Hello @BSFishy! I think https://github.com/opensearch-project/oui/pull/554 has been raised to fix this issue. If you need help with this PR, I would be happy to help

**Comment by BSFishy** [comment]
> Hello @BSFishy! I think #554 has been raised to fix this issue. If you need help with this PR, I would be happy to help

Yes it does look like that PR completes this work, however there are a few PR hygiene things that need to be done for that PR, namely fixing DCO. Feel free to contact @tarunsamanta2k20 if you'd like to help
