### ISSUE TITLE
[Security]Replace nodegit with other more maintained packages

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/oui#539]
nodegit is pretty old. The latest version is 3 years ago and it is not actively maintained. 
right now, it brought us a lot of security issues:
https://github.com/opensearch-project/oui/pull/302
https://github.com/opensearch-project/oui/pull/303

Since it is not maintained by the owners, we need to resolve it. Once there is breaking changes, we are out of the ways to fix the security issue. Therefore, I think we could create an issue to search for possible replace package. Some packages worth explore:

https://github.com/SamyPesse/gitkit-js
https://github.com/isomorphic-git/isomorphic-git (seems best if consider whether it is actively maintained)
https://github.com/es-git/es-git
https://www.npmjs.com/package/simple-git --> https://github.com/steveukx/git-js (osd use this one (simple-git))

nodegit is only used in [this script](https://github.com/opensearch-project/oui/tree/main/scripts/update-token-changelog.js#L128). In this script, it creates git via `const git = require('nodegit');` and calls the following methods listed below. Therefore we need to make sure we have similar functions in the replacement package.
* `git.Repository.open`
* `git.Diff`
* `git.Commit.lookup`
* `git.Reference.nameToId`

Propose 
* delete file scripts/update-token-changelog.js. I don't find it is useful. Even use tag, still see the following error

```
git push origin 1.0.0
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/ananzh/oui.git
 * [new tag]             1.0.0 -> 1.0.0
ubuntu@ip-172-31-55-237:~/work/oui$ yarn update-token-changelog minor
yarn run v1.22.19

$ node ./scripts/update-token-changelog.js minor
[Error: the requested type does not match the type in the ODB] {
  errno: -3,
  errorFunction: 'Tag.lookup'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
* If it is useful, then we should consider replace nodegit to simple-git.

**Comment by AMoo-Miki** [comment]
@ananzh That script is not going to be used by OUI; why not get rid of the script and the dep?

**Comment by ananzh** [comment]
Yeah I am proposing to del it ... @AMoo-Miki 

```
delete file scripts/update-token-changelog.js. I don't find it is useful. Even use tag, still see the following error
```
