### ISSUE TITLE
(OUI Docs) Remove illustration from folders & refereneces to illustration

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#551]
As a follow up to the comment in this pr: https://github.com/opensearch-project/oui/pull/500 - the illustration needs to be removed entirely so it does not show up in the homepage (done) or as the share image, or potentially anywhere else within the project.

**Comment by BSFishy** [comment]
Notably, this line needs to be removed as well: https://github.com/opensearch-project/oui/blob/f5d7aa66fa05e211f60b20cd26612472da9e5ee0/src-docs/src/index.html#LL25C40-L25C134
