### ISSUE TITLE
Implement Pink Elephant

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#556]
As follow-up for #521, since we have an accepted proposal for Pink Elephant, here is the implementation items for Pink Elephant (and more broadly any theme in the future)

 - [x] Create `src/theme_pink_elephant.scss`
    - This should be a copy of `src/theme_dark.scss` with line 13 changed to reflect Pink Elephant rather than dark theme
 - [x] Create `src/themes/oui/oui_colors_pink_elephant.scss`
    - This should be a copy of `src/themes/oui/oui_colors_dark.scss` for now. These colors will change in the future
 - [x] Create `src-docs/src/theme_pink_elephant.scss`
    - This should be a copy of `src-docs/src/theme_dark.scss` with line 16 changed to reflect Pink Elephant rather than dark theme
 - [x] Add Pink Elephant to the list of themes (`OUI_THEMES`) in `src/themes/themes.ts`
    - `text`: `Pink Elephant`
    - `value`: `pink-elephant`
 - [x] Register the theme in `src-docs/src/index.js`
    - Import the theme like the other themes: https://github.com/opensearch-project/oui/blob/f5d7aa66fa05e211f60b20cd26612472da9e5ee0/src-docs/src/index.js#L25-L28
    - Register the theme like the other themes: https://github.com/opensearch-project/oui/blob/f5d7aa66fa05e211f60b20cd26612472da9e5ee0/src-docs/src/index.js#L33-L36

The implementation of this task can be based off the work done here: https://github.com/opensearch-project/oui/compare/main...BSFishy:oui:pink_elephant

**Comment by joshuarrrr** [comment]
@BSFishy Can we close this now? Is there any work remaining to be done?
