### ISSUE TITLE
Update Open Graph url

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#557]
Artifact from when we forked:
https://github.com/opensearch-project/oui/blob/f5d7aa66fa05e211f60b20cd26612472da9e5ee0/src-docs/src/index.html#L26

This url should be changed to `https://oui.opensearch.org/`

**Comment by andreymyssak** [comment]
I see that `https://elastic.github.io/eui` is also used in many other places, f.e. wiki/creating-components-manually.md
```
[docs]: https://elastic.github.io/eui/
```
What I suggest here is adjusting the current task a bit to change to the right URL everywhere.

**Comment by joshuarrrr** [comment]
@andreymyssak There may be some overlapping effort or work in https://github.com/opensearch-project/oui/pull/560

**Comment by andreymyssak** [comment]
@joshuarrrr, @BSFishy Looks like all the work is done, if it is not, note what else is left

**Comment by BSFishy** [comment]
You're right, thanks. Closing this
