### ISSUE TITLE
[Meta] Modern Theme

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/oui#563]
Meta tracking issue for updating our base theme to use the new Cascadia styling. 

All colors, fonts, styling, etc should be updated to use new Cascadia theme. Note: this eng work item is to update the existing base theme. Creating a robust theming system is not tracked by this.

**Comment by KrooshalUX** [comment]
We have this meta issue here: https://github.com/opensearch-project/oui/issues/212

**Comment by BSFishy** [comment]
Clarification - will this be an overhaul of the base `light` and `dark` themes and not new, separate themes?

**Comment by KrooshalUX** [comment]
@BSFishy  that is correct. There have been several threads about a new theme vs changing the base theme. We agreed to revise the base theme, but it is up to you if you want to build a new theming system overall, since the forked one may be have an out of date approach.

**Comment by KrooshalUX** [comment]
Closing this issue in favor of the original meta issue https://github.com/opensearch-project/oui/issues/212 for tracking purposes.
