### ISSUE TITLE
[BUG] [CCI] README Opensearch Logo missing

### ISSUE THREAD

**Issue by timursaurus** [opensearch-project/oui#564]
**Describe the bug**

Opensearch logo file missing in readme.

<img width="452" alt="Screenshot 2023-03-07 at 23 52 49" src="https://user-images.githubusercontent.com/55909427/223507375-44c31014-ebe1-4e55-a934-37a15edce828.png">

**To Reproduce**
1. Go to https://github.com/opensearch-project/oui#readme
2. Clicking on the logo leads to a non-existing file.

**Expected behavior**
Opensearch logo should be displayed as in other repos such as the python repo.

<img width="388" alt="Screenshot 2023-03-07 at 23 55 05" src="https://user-images.githubusercontent.com/55909427/223507973-ca6bbe49-0304-47af-9bdf-4480ef8cd35d.png">

In the [python repo](https://github.com/opensearch-project/opensearch-py/blob/05326ba5474c1a1f5c1975760a4e37037f967dda/README.md?plain=1#LL8-L8C96), the logo file is stored at the root level and linked using an absolute path:
```md
![OpenSearch logo](https://github.com/opensearch-project/opensearch-py/raw/main/OpenSearch.svg)
```

However, in the `oui` repo, the logo file is missing in the root level. The core repo links to an external file:

[OpenSearch readme](https://github.com/opensearch-project/OpenSearch/blob/main/README.md?plain=1#LL1-L1C87)
```md
<img src="https://opensearch.org/assets/img/opensearch-logo-themed.svg" height="64px">
```

Either way of linking the logo should work, but the missing file needs to be added for the first method to work. 

Can I fix this and link to an external resource, like in the core repo?

**Comment by bl1nkker** [comment]
By the way, it is strange that such a problem exists 🤔

**Comment by KrooshalUX** [comment]
> By the way, it is strange that such a problem exists 🤔

Its likely the problem exists because OUI is a fork of another design system, and so are these files. We are working on alignment in approach across repos still.
