### ISSUE TITLE
[CCI] Fix deprecated configuration in webpack.config.js

### ISSUE THREAD

**Issue by SergeyMyssak** [opensearch-project/oui#577]
**Is your feature request related to a problem? Please describe.**

There are some places in `webpack.config.js` that can be improved based on the official webpack documentation.

**Describe the solution you'd like**

1. In the config where we set the rule for `/\.scss$/` we use `loaders` instead of `use`. `rule.loaders` is [deprecated](https://webpack.js.org/configuration/module/#ruleloaders) in favor of `rule.use`. This is an [example](https://v4.webpack.js.org/loaders/sass-loader/) and [docs](https://webpack.js.org/migrate/3/#chaining-loaders) that it was changed in v2 and v3.  

2. `new webpack.NoEmitOnErrorsPlugin()` can be removed from the configuration as they are [default](https://webpack.js.org/migrate/4/#deprecatedremoved-plugins) in production mode. We can use `optimization.noEmitOnErrors` instead of it.

3. We have a condition in `optimization.minimizer`, we can remove it by adding a [special property](https://webpack.js.org/configuration/optimization/#optimizationminimize) `optimization.minimize`.

**Comment by BSFishy** [comment]
This is some phenomenal analysis, thanks for the discovery of this! Great work!
