### ISSUE TITLE
[BUG] Export types for `/lib/test`

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/oui#583]
**Describe the bug**

In OpenSearch Dashboards we use exported test functions such as `findTestSubject` from oui. These however throw type errors because the type is not exposed similar to the components.

**To Reproduce**
1. Go to OpenSearch Dashboards repository 
2. open the file `src/plugins/dashboard/public/application/dashboard_empty_screen.test.tsx`
3. see typescript error

**Expected behavior**
Expose the types for the test functions too

**OpenSearch Version**
3.0
**Dashboards Version**
3.0
**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by Nicksqain** [comment]
Is it necessary to fix the types? After all, you can update the source of the import, since a new module is declared, the reference should be 
`import { findTestSubject } from '@elastic/eui/lib/test/findTestSubject';`

**Comment by joshuarrrr** [comment]
I have some recollection that this has been fixed...

**Comment by joshuarrrr** [comment]
Fixed via https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3798, I believe.
