### ISSUE TITLE
[BUG] [CCI] logo_opensearch.js file is hardcoded

### ISSUE THREAD

**Issue by SergeyMyssak** [opensearch-project/oui#602]
**Describe the bug**

In https://github.com/opensearch-project/oui/pull/380 OpenSearch logo has been added. As far as I understood, `logo_opensearch.js` file was written manually because when we run `compile-icons` command, this file is updated and has different content.

**To Reproduce**
1. `yarn compile-icons`
2. Check changes in `logo_opensearch.js`

**Expected behavior**
`logo_opensearch.js` file should not be updated when running `yarn compile-icons` command

**Screenshots**

<img width="800" alt="Screenshot 2023-03-17 at 10 42 27" src="https://user-images.githubusercontent.com/17855243/225814549-bf7d8798-cc40-44fc-b3c2-ab7efd1303fd.png">

**Host/Environment (please complete the following information):**
 - OS: macOS Ventura 13.2
 - Browser and version: N/A

**Comment by ashwin-pc** [comment]
Nice catch!

**Comment by BSFishy** [comment]
PR has been merged into main :+1:
