### ISSUE TITLE
[BUG] [CCI] tool_tip_example.js: Failed prop type: Invalid prop `size`

### ISSUE THREAD

**Issue by SergeyMyssak** [opensearch-project/oui#607]
**Describe the bug**

In `tool_tip_example.js` file, for `OuiTitle` component, `size` property is specified as `md`, while it should be `m`. Because of this, we get an error in the console:

> Warning: Failed prop type: Invalid prop `size` of value `md` supplied to `OuiTitle`, expected one of ["xxxs","xxs","xs","s","m","l"]. in OuiTitle

**To Reproduce**
1. Launch the application
2. Open the console

**Expected behavior**
There should be no errors in the console

**Screenshots**

<img width="700" alt="Screenshot 2023-03-19 at 16 42 56" src="https://user-images.githubusercontent.com/17855243/226173907-4c78a4b8-36e7-40c8-94c7-48bae2c1d915.png">

**Host/Environment (please complete the following information):**
 - OS: macOS Ventura 13.2
 - Browser and version: N/A

**Comment by ashwin-pc** [comment]
Thanks for catching this one @SergeyMyssak!

**Comment by BSFishy** [comment]
Fixed on main, awaiting backports
