### ISSUE TITLE
[CCI] Replace `Elastic` with `OpenSearch` in the examples

### ISSUE THREAD

**Issue by andreymyssak** [opensearch-project/oui#622]
**Is your feature request related to a problem? Please describe.**

I still see `Elastic` logos and labels on the website, which can be confusing to users (see pictures below).

<img width="500" alt="Basic Card" src="https://user-images.githubusercontent.com/40265277/227228053-694f9d44-dc54-4294-914f-aae21dca5d19.png">
<img width="500" alt="Page" src="https://user-images.githubusercontent.com/40265277/227228157-ca94964d-8b71-4480-9ab5-023d9e20d495.png">
<img width="500" alt="Header" src="https://user-images.githubusercontent.com/40265277/227228173-fe8d30ab-0df6-4812-b3d7-dfd48677a18d.png">

**Describe the solution you'd like**

I propose to replace all `Elastic` logos and labels that are used in the examples and are visible to users on `OpenSearch`.

**Comment by KrooshalUX** [comment]
Thanks for catching these. 

A few quick follow ups and questions: 
- I am not seeing the same "card" example you have screenshot - what page / URL did you find that on?
- In regards to /page, it looks like #177  was closed before all tasks were completed. 
- In regards to /header - it looks like this is realted to https://github.com/opensearch-project/oui/issues/580 and potentially also the blocked PR I had opened. I think @BSFishy  was participating in unblocking my PR

**Comment by andreymyssak** [comment]
@KrooshalUX 
> I am not seeing the same "card" example you have screenshot - what page / URL did you find that on?

https://oui.opensearch.org/1.0/#/display/card#basic-card -> click on the `playground` in the first example

> In regards to /header - it looks like this is related to https://github.com/opensearch-project/oui/issues/580 and potentially also the blocked PR I had opened. I think @BSFishy was participating in unblocking my PR

In https://github.com/opensearch-project/oui/issues/580 we changed the default values, but many examples declare icon names explicitly, so the changes in https://github.com/opensearch-project/oui/issues/580 will only resolve part of the issues.
