### ISSUE TITLE
Add icons to icon pack

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#628]
_This issue supports OSD release 2.7_

The following icons need to be added to OUI & the OUI documentation website - retain the alphabetical order of the Glyphs list.

Use these guidelines for design and adding icons to OUI : https://github.com/opensearch-project/oui/blob/main/wiki/creating-icons.md#style

- [ ] polygon (https://github.com/opensearch-project/oui/issues/309)
- [ ] radial (out of band request, supports maps tools)
- [ ] visBuilder (https://github.com/opensearch-project/ux/issues/45)
- [ ] visBuilderSavedObject (https://github.com/opensearch-project/oui/issues/637) to represent the visualizations created in Observability visualizations in the Saved Objects table. 
- [ ] visQueryDQL (https://github.com/opensearch-project/ux/issues/45) (this is a strategic have-in-back-of-pocket)
- [ ] visQueryPPL (https://github.com/opensearch-project/oui/issues/637)
- [ ] visQueryPromQL (https://github.com/opensearch-project/oui/issues/637)
- [ ] visQuerySQL (https://github.com/opensearch-project/oui/issues/637)

**Comment by canascar** [comment]
Glyphs for GeoMap draw tools: radial.svg / polygon.svg
![radial](https://user-images.githubusercontent.com/111922174/229249824-7bbcc162-a99e-45f0-b961-87a58bce97cb.svg)
![polygon](https://user-images.githubusercontent.com/111922174/229249825-26f5d3ae-2cb0-4449-a938-389d3a23f156.svg)

**Comment by KrooshalUX** [comment]
![visBuilder](https://user-images.githubusercontent.com/105819041/229259259-1a65ae7a-2703-4ea4-ba42-9c09a153550f.svg)
![visBuilderDQL](https://user-images.githubusercontent.com/105819041/229259262-5ead97b8-44d3-404f-a285-50f8a123a3f6.svg)
![visBuilderSQL](https://user-images.githubusercontent.com/105819041/229259267-9cd925c1-13e5-4e14-b7ea-e3b2b0d37178.svg)
![visBuilderPPL](https://user-images.githubusercontent.com/105819041/229259269-9e12f6fc-e30a-4443-9570-3f3a8d58ff71.svg)

![visBuilderPromQL](https://user-images.githubusercontent.com/105819041/229259271-0bf34764-c78c-4dc5-b550-cc60f9895255.svg)

**Comment by KrooshalUX** [comment]
![visBuilder](https://user-images.githubusercontent.com/105819041/229259418-f56ddd8f-e189-40b1-9559-43a435121d2b.svg)
![visBuilderDQL](https://user-images.githubusercontent.com/105819041/229259419-f42aecfc-672f-4686-9ef6-690815ac990f.svg)
![visBuilderPPL](https://user-images.githubusercontent.com/105819041/229259420-368de8ef-0f09-44a8-b6d9-405857f1f9e7.svg)
![visBuilderPromQL](https://user-images.githubusercontent.com/105819041/229259421-c788329d-e0f4-4d2e-8e08-320aecc6a109.svg)
![visBuilderSavedObject](https://user-images.githubusercontent.com/105819041/229259422-26be98b4-3300-4166-8ca1-b0da070dd6f8.svg)
![visBuilderSQL](https://user-images.githubusercontent.com/105819041/229259423-51a61f72-2bc7-4a27-a5f4-e04b66050ce4.svg)

**Comment by KrooshalUX** [comment]
@BSFishy all icons for the 1.1 release are here in the comments. Please refer to https://github.com/opensearch-project/oui/blob/main/wiki/creating-icons.md#style on next steps

**Comment by canascar** [comment]
![polygon](https://user-images.githubusercontent.com/111922174/229261929-e2978766-9232-48cb-a8a0-8c800b41fc98.svg)
![radius](https://user-images.githubusercontent.com/111922174/229261930-3408d89b-62a5-4f79-be2a-a9d901b98acc.svg)

**Comment by canascar** [comment]
![polygon](https://user-images.githubusercontent.com/111922174/229262078-d3bd9353-65ea-4aef-b520-4e4456867a51.svg)
![radius](https://user-images.githubusercontent.com/111922174/229262080-06f938da-2502-4748-b473-997273e135da.svg)

**Comment by canascar** [comment]
Reworked the visbuilder icons as there was a discrepancy in the lettering of "PPL" - all reworked versions in the .ip file below. @KrooshalUX please review. 
[visBuilder.zip](https://github.com/opensearch-project/oui/files/11129820/visBuilder.zip)
<img width="710" alt="visBuilderIcons" src="https://user-images.githubusercontent.com/111922174/229296496-382311cd-e9e7-4e4d-88ac-b81dddeccca2.png">

**Comment by BSFishy** [comment]
I did some cleanup to the final SVG files:
 1. Add SPDX header
 2. Indent paths
 3. Remove fills on paths
 4. Re-order `svg` tag
 5. Remove fill on `svg` tag

(for reference)

**Comment by KrooshalUX** [comment]
Thanks @BSFishy - wondering if we should use that to update anything on this doc:  https://github.com/opensearch-project/oui/blob/main/wiki/creating-icons.md#style - I think earlier you mentioned you had some ideas.

Also for SOP-ifying this: I would like to keep UX out of preparing the files beyond the original export, in case a mistake is made while editing. Otherwise, engineering would need to wait for UX to re-export, this way engineering has the original export and can modify as necessary with less likelihood of errors.

**Comment by BSFishy** [comment]
> Thanks @BSFishy - wondering if we should use that to update anything on this doc: https://github.com/opensearch-project/oui/blob/main/wiki/creating-icons.md#style - I think earlier you mentioned you had some ideas.

I think it is mostly covered in [the Clean the SVG section](https://github.com/opensearch-project/oui/blob/main/wiki/creating-icons.md#clean-the-svg). I can submit a PR to update it with more detailed info from what I did for these icons.

> Also for SOP-ifying this: I would like to keep UX out of preparing the files beyond the original export, in case a mistake is made while editing. Otherwise, engineering would need to wait for UX to re-export, this way engineering has the original export and can modify as necessary with less likelihood of errors.

I agree. I wanted to update this issue for knowledge sharing reasons for the future.

**Comment by KrooshalUX** [comment]
Updated names as per feedback from pull request #658
