### ISSUE TITLE
[Research] Research the usage of package `node-sass` in OUI

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/oui#633]
Research the usage of package `node-sass` in OUI and determine if we can get rid of this dependency.

Reason: `node-sass` depends on `request` which is deprecated and causing #630

**Comment by BigSamu** [comment]
@joshuarrrr I would like to take this issue. Currently working on issue #595 with @BSFishy to clean up dependencies.

**Comment by BSFishy** [comment]
I think this _should_ have been removed in #1001, but we should still make sure we have removed all remnants

**Comment by BigSamu** [comment]
@BSFishy,

Upon review of the base code, the only place where we still see `node-sass` is under the `react-datepicker` package at `./packages/react-datepicker/package.json`. Below a screenshot from the search (of course without considering the results of CHANGELOG.md)

<img width="1358" alt="image" src="https://github.com/opensearch-project/oui/assets/28614451/02d92dda-e7c0-4787-895b-573df731e783">
 
 Should we get rid of this dependency on this file + the related scripts?
 
 Regards,
 
 Samuel

**Comment by BSFishy** [comment]
> Should we get rid of this dependency on this file + the related scripts?

I'm hesitant to do that in `react-datepicker`. We currently have a built bundle for it, but don't want to cut ourselves off in the future if we want to build a new one.

**Comment by BigSamu** [comment]
> > Should we get rid of this dependency on this file + the related scripts?
> 
> I'm hesitant to do that in `react-datepicker`. We currently have a built bundle for it, but don't want to cut ourselves off in the future if we want to build a new one.

Ok @BSFishy, I did some further investigation and indeed the [last release](https://github.com/Hacker0x01/react-datepicker/) (version 4.21) does not use `node-sass` package but instead `sass` package (check [here](https://github.com/Hacker0x01/react-datepicker/blob/main/package.json#L87)). In the OUI base code, I see that the version for `react-datepicker` package is 2.0, if I am not wrong.

So what I did was download the last release of `react-datepicker`, create the bundle and replace the new JS file in `./pacakges` folder (`.packages/react-datepicker.js`)

**Comment by BigSamu** [comment]
Hi @joshuarrrr, @BSFishy,

I would appreciate your feedback on my last message! Just to see how we should proceed!

Regards,

Samuel

**Comment by BSFishy** [comment]
Yeah I think this is a difficult one. react-datepicker has been a task in the backlog for a while (#205). I think it's going to be difficult to upgrade it while making sure nothing breaks. I think we had a few conversations about possible options but ultimately landed on leaving the package the way it is. I can't find anything on Github right now but @AMoo-Miki might have more context

**Comment by BigSamu** [comment]
Thanks @BSFishy. Let's wait for what @AMoo-Miki suggest. But regardless of what we decide, I think this issue is resolved regarding the research of `node-saas` package and its usage in OUI.

**Comment by BSFishy** [comment]
Closing since the original objective of this issue has been achieved. If there is any followup work, a new issue can be created.
