### ISSUE TITLE
Deprecate `iconType` and `iconProps` from `OuiPageHeader`

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#644]
As including an icon in our page header is not part of our guidance moving forward, we should deprecate the use of `iconType` and `iconProps` from `OuiPageHeader`, as well as update the corresponding OUI documentation page (remove the props from the props tab, and in any of the playground areas it may still be visible). 
 
 Thanks to @joshuarrrr for the suggestion!
 
              @KrooshalUX Do we want a follow-up issue to actually remove/deprecate the `<OuiPageHeader>` `iconType` prop?

_Originally posted by @joshuarrrr in https://github.com/opensearch-project/oui/issues/625#issuecomment-1489022971_

**Comment by curq** [comment]
Can I take this issue please?

**Comment by BSFishy** [comment]
For reference, this work should be done in 2 PR's:
 1. Deprecate the prop by adding a doc comment and a console warning
 2. Actually remove the prop

This will make sure we can backport the deprecation
