### ISSUE TITLE
Update Node version

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#646]
We need to start working on updating the version of Node we use. The version of Node that we use is currently EOL. We need to work on updating to Node `18.15.0`. There are potentially some blockers in the way of this. For example, currently Webpack 4 is blocking, as it doesn't support newer versions of Node. We will either need to update it or replace it before we're able to update Node.

**Comment by jmetev1** [comment]
seems like only thing to update is nvmrc. 
 package.json has   "docker_image": "node:10" but i left that alone since no one else has been updating it
