### ISSUE TITLE
[CCI] Remove unused chart theme code and imports

### ISSUE THREAD

**Issue by SergeyMyssak** [opensearch-project/oui#656]
**Is your feature request related to a problem? Please describe.**

The charts theme code was removed as a part of the [PR](https://github.com/opensearch-project/oui/pull/554), but we still have unused code that can be removed (code in `compile-oui.js` and imports in `src-docs`).

**Describe the solution you'd like**

Remove unused chart theme code and imports

**Comment by joshuarrrr** [comment]
closed via #657
