### ISSUE TITLE
Remove "Elastic" Keyword References 

### ISSUE THREAD

**Issue by kaddy645** [opensearch-project/oui#67]
Remove and Replace all the "Elastic" References with "OpenSearch" or "Appropriate Keyword"

**Comment by bandinib-amzn** [comment]
@KrooshalUX As doc site hosting is near finish line, we need to remove or replace "Elastic" reference from all documents? Should we replace with "Opensearch"?

These are references: https://github.com/opensearch-project/oui/search?l=Markdown&q=Elastic

**Comment by KrooshalUX** [comment]
Thanks for asking @bandinib-amzn - This should be assigned to me. As discussed with @kaddy645 and @AMoo-Miki last week I will be performing text and imagery edits locally and making appropriate PRs. @AMoo-Miki and I have been working on that process.

**Comment by bandinib-amzn** [comment]
Thank you for clarification @KrooshalUX. Looking forward to PRs.

**Comment by KrooshalUX** [comment]
Note: No changes should be made to [/CHANGELOG.md](https://github.com/opensearch-project/oui/blob/069f87834fa095b177e0cb38899dd445f9954b84/CHANGELOG.md), as it accurately describes changes to EUI 34.6 and all previous versions.

**Comment by KrooshalUX** [comment]
Closing because this is duplicate of a more comprehensive issue

**Comment by KrooshalUX** [comment]
Closing because this is duplicate of a more comprehensive issue
