### ISSUE TITLE
Host OUI- Doc Site

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/oui#68]
Create CodePipeline and host OUI Doc Site

**Comment by kavilla** [comment]
This sprint: CDK.

**Comment by kaddy645** [comment]
CDK Is deployed over opensearch infra

doc-site : https://oui.1291fa08092a4a2dfd6d43f11d7bbcf3f22bf569.opensearch.org/latest/#/
note : Needs pretty URL

**Comment by kavilla** [comment]
[Planning]

In staging
