### ISSUE TITLE
[BUG] Release workflow is missing 2PR approval process

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/oui#691]
**Describe the bug**

Adding this issue as bug because the current 1-click process in this repository lacks this feature. See details here https://github.com/opensearch-project/opensearch-build/issues/3111
Sample PR: https://github.com/opensearch-project/opensearch-java/pull/383

**To Reproduce**
Push a tag to this repo and see the product get released

**Expected behavior**
The release-drafter workflow should be blocked asking for approval from 2 maintainers/codewoners to approve the release.

**Comment by BSFishy** [comment]
Fixed in #686
