### ISSUE TITLE
[CCI] Move OuiBottomBar default inline styles to the CSS file

### ISSUE THREAD

**Issue by SergeyMyssak** [opensearch-project/oui#693]
**Is your feature request related to a problem? Please describe.**

It is not possible to override the position of `OuiBottomBar` component without `!important` in the CSS file because the component uses inline styles. We have the option of not using `!important` in our styles, but then we would have to remove the default inline styles and use them in the CSS file so we have more flexibility.

**Describe the solution you'd like**

Move default inline styles to the CSS file

**Additional context**

The need for this issue was caused by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3804, and may also be caused in the future by something similar.

**Comment by joshuarrrr** [comment]
@SergeyMyssak Thanks so much for opening the issue and PR over here!

**Comment by SergeyMyssak** [comment]
We can close this issue as https://github.com/opensearch-project/oui/pull/694 has been merged
