### ISSUE TITLE
[BUG] Refreshing option list onFocus or onClick of ComboBox 

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#696]
_This issue may be lacking technical implementation detail as I am filing on behalf of a contractor using passed-on messages via Slack. This is not a live project, but a project in development and implementation issues are popping up when trying to use ComboBox within the outlined user scenario._

User scenario: During the set up of an alert monitor using the quick create flow, I see an option to send alerts to a channel. However, I do not yet have the correct channel configured, so I click "Manage Channels" and I see an interface where I can configure a new channel. When I return to the alerting quick-create flow, I expect that my newly configured channel will appear in the ComboBox menu. On click, I (should) see the ComboBox UI change to a loading state while the list of configured channels is loaded, and see the list that includes my newly configured channel. 

![Screenshot 2023-04-11 at 1 38 06 PM](https://user-images.githubusercontent.com/105819041/231282696-5bf38727-4f7f-45a8-bd6d-5594fc2e8ac0.png)

------
Notes from the engineer trying to implement this:
 - Trying to use onClick or onFocus to refresh the channel list is causing an issue where the user would need to click the ComboBox twice. This is not the desired experience , the user should only have to click once. 
 - This appears to be an issue that was present in the version of EUI that OUI is forked from (EUI 34.6)

**Comment by KrooshalUX** [comment]
Additional note: once this bug is addressed , we will need to cut a release so the Anywhere project engineers can uptake the change. Thanks!

**Comment by sikhote** [comment]
I can provide a sandbox to recreate—I'll do this soon. Thanks @KrooshalUX .

**Comment by KrooshalUX** [comment]
@sikhote thanks - please ping @BSFishy as well when that is ready - he and I spoke about this issue this morning and how he might be able to start to create POCs to find the fix.

**Comment by AMoo-Miki** [comment]
I am not sure I follow the problem but the way I would build this is:
* open the new page when "Manage channels" is clicked
* when channels change, i use `postMessage` to inform the main page to reload the list and populate the combo-box.

> I expect that my newly configured channel will appear in the ComboBox menu.
This doesn't happen magically and loading the list when the combo is focused or opened is not good user experience.

In other words, this is not a problem of the combo-box.

**Comment by AMoo-Miki** [comment]
Thanks @sikhote for the sandbox. That UX is what I was afraid the original post was talking about; I would strongly discourage against this UX.

My proposal is to choose one of these:
1. [Better] When the page hosting the combo is loaded for the first time, have it fetch the options and feed it to the combo. Use the [MessageEvent ](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to listen for update commands from another window/tab.
2. [Acceptable] Have a refresh button next to the combo. Populate it when page loads but let the user trigger reloading whenever they want.
3. [Best] Combine both of the above.

**Comment by kamingleung** [comment]
@KrooshalUX @AMoo-Miki Consider repurposing this issue as an Enhancement to the ComboBox component instead of a bug (Today, OUI doesn't support dynamically loading selections of a comboBox, right?)

However, workflows in OpenSearch often involve multiple personas. There is a need to be able to serve the latest available selections. For example, an admin may be creating new notification channels or index patterns. On the other hand, analysts may be picking the latest data available to them. We should work towards a seamless experience for users, they should not have to worry about if the data is outdated or not.

**Comment by KrooshalUX** [comment]
@AMoo-Miki - Clarification on #1 - Does this only work on load of the page? My concern with this approach is that it does not satisfy the scenario that lead us to this discovery / the one outlined in the issue where the user is opening a manage screen in another tab/window, returns to this tab/window and *then* clicks on the ComboBox. 

We *very much* want to avoid the refresh button. This is a confusing experience and is an outdated approach (as you have it marked "archaic").

**Comment by KrooshalUX** [comment]
+1 to @kamingleung statement above. Multiple users creating new options is not entirely an "edge case" - there are various scenarios that have come to our attention for simultaneous and collaborative workflows. It is my understanding that only ComboBox is affected, and other components like Select and SuperSelect arent impacted by any sort of limitation, further highlighting this interaction issue.

**Comment by kamingleung** [comment]
> I talked about this situation with the team today. For now, it seems we will be sticking with the UX flow for the implementation this is already implemented, understanding that the loading animation will not be present.
> 

Side note:
@sikhote Do you mind creating a codesandbox on how that would work without the loading animation? That would be super helpful. Thanks.

**Comment by sikhote** [comment]
@kamingleung here is a sandbox that shows off the behavior our implementation is currently using. In the sandbox, the select starts with 1 option, but as soon as it is clicked, another option is loaded in asynchronously. In this sandbox, the `isLoading` prop is not used, so the user has a good UX experience. Hope that helps!

https://codesandbox.io/s/laughing-booth-ow969k?file=/index.js

**Comment by BSFishy** [comment]
I'm sorry, I don't see an issue with the latest sandbox posted. It seems to work properly from what I can tell. Additional options are added correctly, only one click is necessary, etc.

**Comment by sikhote** [comment]
@BSFishy correct, in the sandbox above I have removed the `isLoading`, which allows the UX to work as expected. In the first sandbox, it does not work as expected.

**Comment by KrooshalUX** [comment]
@BSFishy bumping this issue - we have 2 more experiences being delivered that would also need this resolved for refreshing the list available based on processes happening in another window (or another instance)

**Comment by BSFishy** [comment]
I still don't understand what the bug is. Could this be rewritten in the format of "this is what I'm trying to do in a minimal example", "this is what I would expect to happen", and "this is what actually happens"? Emphasis on minimal example; it's difficult to understand exactly what you're trying to do when involving a bunch of other higher level concepts.

**Comment by BSFishy** [comment]
I figured it out. It was calling the focus function twice because `onFocus` was being added to an element it shouldn't. Creating a PR soon
