### ISSUE TITLE
(OUI Docs) Remove Elastic References from OuiBasicTable Actions examples

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#697]
Section: "Adding actions to table" 

In default example, on all rows: 
- [ ] Replace "elastic.co" in tooltip with "opensearch.org" 
- [ ] Replace "https://elastic.co" in the link action with "https://opensearch.org" 
![Screen Shot 2023-04-11 at 12 28 22 PM](https://user-images.githubusercontent.com/105819041/231314275-9994a15d-0f7e-467e-9463-5b8248028fbb.png)

Then, toggle the option for "multiple actions" example , on all rows:
- [ ] Replace "elastic.co" in popover menu with "opensearch.org"
- [ ] Replace Elastic logo with OpenSearch logo
- [ ] Replace "http://elastic.co" with "https://opensearch.org" 
![Screen Shot 2023-04-11 at 12 28 15 PM](https://user-images.githubusercontent.com/105819041/231314289-198b6b1f-5606-40d7-acfd-ae63a24a5ef4.png)

**Comment by SergeyMyssak** [comment]
Hello @KrooshalUX, this issue is partially fixed, we just need to backport https://github.com/opensearch-project/oui/pull/623. As a result, we do not have this problem on the main branch:

<img width="600" alt="Screenshot 2023-04-18 at 08 31 45" src="https://user-images.githubusercontent.com/17855243/232656009-dcd3fce2-f9b5-4e2d-bed4-79eb10cb2e77.png">


I raised another PR - https://github.com/opensearch-project/oui/pull/721 to fix the link in a single action.

**Comment by SergeyMyssak** [comment]
On version 1.0 everything works as it should:

<img width="600" alt="Screenshot 2023-05-10 at 09 50 07" src="https://github.com/opensearch-project/oui/assets/17855243/f44ed2f1-e646-4bf5-86f0-e6a38744f4a3">
<img width="600" alt="Screenshot 2023-05-10 at 09 50 28" src="https://github.com/opensearch-project/oui/assets/17855243/3ed5fbb8-900d-42e0-aaa1-158abab46782">

---

On version 1.1 there are no changes related to the link in a single action (https://github.com/opensearch-project/oui/pull/721):

<img width="600" alt="Screenshot 2023-05-10 at 09 54 19" src="https://github.com/opensearch-project/oui/assets/17855243/4bcea710-700b-4ee1-bd61-76b34a5ffa04">
<img width="600" alt="Screenshot 2023-05-10 at 09 55 56" src="https://github.com/opensearch-project/oui/assets/17855243/fb75d9fe-4b86-4023-8dfc-ad25f2c66e45">

**Comment by SergeyMyssak** [comment]
On versions 1.0, 1.1, and 1.2 everything works as it should. For 1.1 version the necessary changes were backported and applied.
<img width="700" alt="Screenshot 2023-06-21 at 12 28 18" src="https://github.com/opensearch-project/oui/assets/17855243/6e15262c-a939-4d6f-b7a4-408ccf7c8bae">
