### ISSUE TITLE
Implement dropdown to choose different OUI Versions

### ISSUE THREAD

**Issue by kaddy645** [opensearch-project/oui#73]
TODO:

Get proposal how we will be versioning.

---
Allow user to choose OUI Doc Site from different versions

### SC
<img width="1792" alt="Screen Shot 2022-09-16 at 9 47 15 AM" src="https://user-images.githubusercontent.com/32860683/190689179-65f7b04a-a935-41b0-a671-2c2a41249870.png">

**Comment by kaddy645** [comment]
Update: Add web component to OUI Doc Site to implement this feature

**Comment by BSFishy** [comment]
Merged :)
