### ISSUE TITLE
[BUG][CCI]  FAQ.md has wrong link to licence

### ISSUE THREAD

**Issue by Aigerim-ai** [opensearch-project/oui#738]
Can I use OUI? [FAQ.md](url)  refers to  [https://github.com/opensearch-project/oui/blob/main/LICENSE](url)

<img width="1433" alt="Screenshot 2023-04-26 at 19 26 03" src="https://user-images.githubusercontent.com/26738268/234589758-32aea4ff-c3f0-42e6-b9b5-d4f67cec6b4e.png">

instead of [https://github.com/opensearch-project/oui/blob/main/LICENSE.txt](url)

**Comment by joshuarrrr** [comment]
@Aigerim-ai Do you want to be assigned to this?

**Comment by curq** [comment]
Hi @joshuarrrr If the issue is available, can I take it?

**Comment by Aigerim-ai** [comment]
@joshuarrrr  Yes, thank you!

**Comment by joshuarrrr** [comment]
In this case, I'll give it to @Aigerim-ai, since they opened the issue.
