### ISSUE TITLE
(OUI Docs) Add link to figma community 

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#739]
The UX team has published the OUI Component Library in Figma and has made it available to the community. To guide designers and contributors to the file, a link to the Figma community file should be placed in the OUI documentation site header. 

- [ ] Add Figma logo SVG to header as a link , to the right of the GitHub icon (asset : https://github.com/opensearch-project/oui/blob/main/src-docs/src/images/logo-figma.svg) 
- [ ] Tooltip on hover: Figma component library
- [ ] URL: https://www.figma.com/community/file/1240039515407642648

**Comment by navinkrv** [comment]
i want to contribute to this issue please assign me

**Comment by navinkrv** [comment]
sorry for this but please assign it to another person

**Comment by MadaniKK** [comment]
Hi! I would like to contribute to this issue. Thank you!
