### ISSUE TITLE
Enable Alert component in OUI

### ISSUE THREAD

**Issue by rednaksi91** [opensearch-project/oui#740]
**Is your feature request related to a problem? Please describe.**
The Material UI (MUI) library provides a rich set of pre-built components, including the <Alert/> component, which can be used with a single line of code. The <Alert/> component is highly customizable and comes with a range of pre-defined styles and variants that can be easily applied.

On the other hand, OUI does not have a pre-built <Alert/> component. Developers using OUI would need to combine the Text, Popup, and Icons components to create custom alerts that match their specific requirements. This can be a more time-consuming process and may require more code and customization.

**Describe the solution you'd like**
Including an <Alert/> component in OUI could potentially simplify development and improve efficiency for developers. It would provide a standardized way of displaying alerts across OUI applications and reduce the amount of custom code required to create alerts.

**Describe alternatives you've considered**
However, it's worth noting that adding a new component to a UI library requires careful consideration and testing to ensure that it aligns with the library's design principles and meets the needs of its users. It's possible that the OUI development team has chosen not to include an <Alert/> component because it doesn't align with the design principles of the library, or because there are other more pressing priorities for the development team.

**Comment by BSFishy** [comment]
OUI has the callout component: https://oui.opensearch.org/1.1/#/display/callout

Same functionality, just a different name.
