### ISSUE TITLE
[BUG](OUI Docs) Changes to Page not carried over from 1.0 to 1.1 

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#746]
With #625 , icons were removed from page header examples in 1.0, however the icons are present in the 1.1 website example. 

![Screen Shot 2023-05-02 at 12 44 06 PM](https://user-images.githubusercontent.com/105819041/235769773-bd103bbf-3af3-45e1-8bac-4af0f63d9502.png)
![Screen Shot 2023-05-02 at 12 44 21 PM](https://user-images.githubusercontent.com/105819041/235769781-ca8a2fd8-5d8b-4938-a2c9-b4b14e12bfaa.png)

**Comment by BSFishy** [comment]
Backport for the PR that fixed this failed. Need to figure out why so we can remedy

**Comment by SergeyMyssak** [comment]
The necessary PR (https://github.com/opensearch-project/oui/pull/754) was merged, and the bug is fixed

<img width="700" alt="Screenshot 2023-06-26 at 10 03 16" src="https://github.com/opensearch-project/oui/assets/17855243/444e093f-d980-4ed4-9653-6388b0d0e805">
