### ISSUE TITLE
(OUI Docs) Audit - Changes in 1.0 not carried over to 1.1

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#747]
I suspect that there are several more changes from 1.0 that did not carry over to 1.1. Is it possible to look into the differences between 1.0 and 1.1 from an engineering perspective before we consider putting a UX resource on a visual 1:1 audit? 

Here are two so far : 
#745  #746

**Comment by KrooshalUX** [comment]
@BSFishy  with the latest PR approvals for the backport issue, should this and #745 and #746 be closed?

**Comment by BSFishy** [comment]
Yes. And if there's nothing else for this issue, it can be closed as well
