### ISSUE TITLE
Preliminary clean up of `react-datepicker` package

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#766]
The `react-datepicker` package is a fork of the NPM package with some visual changes to make it fit better into OUI. However, that means that a lot of it isn't necessary at all. This task is to remove some of the things that we don't need.

(paths will be relative to `packages/react-datepicker` unless otherwise stated)

 - [ ] Delete unnecessary folders & add them to a `.gitignore`
    - [ ] `docs/`
    - [ ] `docs-site/`
    - [ ] `examples/`
 - [ ] Remove `highlight.js` from dependencies

**Comment by BigSamu** [comment]
@BSFishy @joshuarrrr may I take this issue?

**Comment by BSFishy** [comment]
Sure, it looks like someone else tried to do this, but it looks like that became stale. Take a look at #769 to see where it left off

**Comment by BigSamu** [comment]
> The `react-datepicker` package is a fork of the NPM package with some visual changes to make it fit better into OUI. However, that means that a lot of it isn't necessary at all. This task is to remove some of the things that we don't need.
> 
> (paths will be relative to `packages/react-datepicker` unless otherwise stated)
> 
> * [ ]  Delete unnecessary folders & add them to a `.gitignore`
>   
>   * [ ]  `docs/`
>   * [ ]  `docs-site/`
>   * [ ]  `examples/`
> * [ ]  Remove `highlight.js` from dependencies

@BSFishy 

Following this issue, if we delete the folders `docs/`, `docs-site/` and `examples/`, why is needed to add them in the `.gitignore` file?

Also, upon review of the `packages/react-datepicker` folder, I did not find any file named `highlight.js`. Any suggestions on this?

Regards,

Samuel

**Comment by BSFishy** [comment]
> Following this issue, if we delete the folders `docs/`, `docs-site/` and `examples/`, why is needed to add them in the `.gitignore` file?

You're right, I was worried about these being built artifacts, so I wanted to add them to `.gitignore` to make sure they wouldn't get added again in the future. I updated the original PR but not this issue, nice catch!

> Also, upon review of the `packages/react-datepicker` folder, I did not find any file named `highlight.js`. Any suggestions on this?

There is a dependency on this, that if I'm not mistaken is unused now:

https://github.com/opensearch-project/oui/pull/769/files#diff-41bb100291761acc256d5be51f3cad2bd1e512a608ca52235d44af5603a88637

**Comment by BigSamu** [comment]
@BSFishy, got it! Changes added in PR #1067

**Comment by BSFishy** [comment]
Fixed in #1067
