### ISSUE TITLE
OUI-Codepipeline CDK

### ISSUE THREAD

**Issue by kaddy645** [opensearch-project/oui#77]
Create CDK to deploy codepipeline , which we will use to deploy oui doc-site to s3.

**Comment by kaddy645** [comment]
Update: 

- CDK is ready & Deployed over opensearch-infra. 
- Ticket is pending for creating new repo to deploy CDK
- Pipeline is ready
- Doc Site is Up & Running [Site](https://oui.1291fa08092a4a2dfd6d43f11d7bbcf3f22bf569.opensearch.org/latest/)

**Comment by joshuarrrr** [comment]
Are we going to eventually have a nicer human-readable URL?

**Comment by kaddy645** [comment]
Will update CDK to handle staging + prod.

**Comment by BSFishy** [comment]
[Repo is live!](https://github.com/opensearch-project/oui-docs-cdk)
