### ISSUE TITLE
Page Header docs still use Kibana logo

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/oui#772]
The page header docs still use the Kibana logo for the first example. The logo should be removed entirely

**Comment by KrooshalUX** [comment]
@BSFishy - there shouldnt be a logo there at all - https://github.com/opensearch-project/oui/issues/178 

We also deprecated the use of logo / icon in the page header here  :https://github.com/opensearch-project/oui/issues/644

**Comment by BSFishy** [comment]
Thanks for the context. Closed as duplicate of #178
