### ISSUE TITLE
Add Anomaly Detection icon to OUI glyph set

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#780]
_This issue supports OSD release 2.8_

The following icons need to be added to OUI & the OUI documentation website - retain the alphabetical order of the Glyphs list.

Use these guidelines for design and adding icons to OUI : https://github.com/opensearch-project/oui/blob/main/wiki/creating-icons.md#style

- [ ] anomalyDetection

![Anomaly detection-V2](https://github.com/opensearch-project/oui/assets/105819041/40571fe0-d065-49e9-9893-2dd212987fb2)

**Comment by KrooshalUX** [comment]
cc @amitgalitz

**Comment by BSFishy** [comment]
Will submit PR tomorrow ASAP
