### ISSUE TITLE
[BUG] [CCI] Update the default branch in changelog.js 

### ISSUE THREAD

**Issue by andreymyssak** [opensearch-project/oui#797]
**Describe the bug**

The default branch is now `main` and therefore the `main` section is not removed from the changelog.

https://github.com/opensearch-project/oui/blob/ce8acf41cc58cccbef180d1d93e0025e29e4a312/src-docs/src/views/package/changelog.js#L17-L20

**To Reproduce**
1. Open http://localhost:8030/#/package/changelog
2. See the `main` section

**Expected behavior**
The main section must be hidden

**OpenSearch Version**
Main branch (localhost)

**Screenshots**
<img width="1728" alt="Screenshot 2023-05-29 at 11 17 36" src="https://github.com/opensearch-project/oui/assets/40265277/84a240f1-67c9-48d2-b459-0a1221634d2d">

**Comment by BigSamu** [comment]
@joshuarrrr @BSFishy,

I would like to work on this issue

**Comment by BSFishy** [comment]
Oops, sorry @BigSamu this is worked on in #1050. Forgot to tag the issue!

**Comment by BigSamu** [comment]
No worries @BSFishy ! Thanks for letting me know!
