### ISSUE TITLE
[BUG] Kibana logo on page header component in docs

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/oui#800]
**Describe the bug**

in OUI doc site 1.2 the Kibana logo exists. It also exists on 1.1 and 1.0 versions of the site

**To Reproduce**
1. Go to https://oui.opensearch.org/1.2/#/layout/page-header

**Expected behavior**
The logo should not exist

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**
<img width="1079" alt="Screenshot 2023-05-31 at 11 30 32 AM" src="https://github.com/opensearch-project/oui/assets/20453492/494f7c47-3e9f-4e50-8dcf-1cc4f1936ed0">

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by BSFishy** [comment]
closing as dup
