### ISSUE TITLE
Disable emoticon in markdown renderer by default

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/oui#802]
**Is your feature request related to a problem? Please describe.**

The markdown renderer is rendering emoticons by default. Markdowns are generally used to show messages/documentations (in opensearch-project), it would be surprising to see something like `index-partition` turns into `inde😝artition`. If user wants to show emojis, they can do something more explicit like `:smile:`, or override the default parsing plugin to enable emoticon.

**Describe the solution you'd like**

Disable emoticon by default.

**Describe alternatives you've considered**

Do this

```typescript
      const parsingPlugins = getDefaultOuiMarkdownParsingPlugins() as Array<[any, any]>; // Array<unified.PluginTuple<any[], unified.Settings>
      const emojiPlugin = parsingPlugins.find(([, settings]) => settings.emoticon)?.at(1);
      if (emojiPlugin) emojiPlugin.emoticon = false;
      return (
        <EuiMarkdownFormat parsingPluginList={parsingPlugins}>
          {props.message.content}
        </EuiMarkdownFormat>
      );
```

**Additional context**

https://github.com/opensearch-project/oui/pull/801

**Comment by joshuarrrr** [comment]
I'm inclined to agree with this, primarily because the documentation for Markdown Format explicitly mentions emojis sever times, but does not mention emoticons.

Have you actually validated the `index-partition` example, though? I'd expect a parser to ignore that and only convert complete word emoticons (`:)` but not `foobar:)`).

**Comment by joshuarrrr** [comment]
Ha, I confirmed the parser is that dumb in https://oui.opensearch.org/1.0/#/editors-syntax/markdown-editor . OK, now I'm convinced it's a bug not an enhancement.

**Comment by AMoo-Miki** [comment]
I agree with you all; it is a bug.
