### ISSUE TITLE
Remove the "Widths" section from the OuiModal docs

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/oui#803]
In https://oui.opensearch.org/1.0/#/layout/modal, we have a section about how to manually specify widths via inline styles. This seems like a bit of an antipattern, and not something we want to encourage. See https://github.com/opensearch-project/oui/issues/783 for examples where we do customize modal widths today. 

If we _do_ want to allow direct sizing controls, we probably want to add more props. Otherwise, I think we should just scratch the section altogether.
<img width="1062" alt="Screen Shot 2023-06-08 at 5 38 03 PM" src="https://github.com/opensearch-project/oui/assets/1679762/f12cb3f6-6c2d-4cfe-8d37-9b18c61dbf11">

**Comment by KrooshalUX** [comment]
I agree that we should remove this guidance - it does not align with the Design System directive to rely on the responsive system as much as possible out of the box.

**Comment by BigSamu** [comment]
@joshuarrrr @BSFishy can I take this issue?

**Comment by BSFishy** [comment]
Yep, looks like this is ready to pick up

**Comment by BSFishy** [comment]
Fixed in #1066
