### ISSUE TITLE
Look & Feel - Sass variable value changes for research

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#807]
In the interest of delivering an impactful but quick change to look & feel of the OpenSearch Dashboards product, the UX team has determined an update to **existing** Sass variable values.

Proposed changes visualized: 
![Screen Shot 2023-06-12 at 4 43 46 PM](https://github.com/opensearch-project/oui/assets/105819041/979e9ae3-6635-4018-bac3-74d25963af0f)

**UI COLORS**
- Knowing that there are various aliased uses of these base colors, and that shading/tinting may occur these colors for the various uses (ex: ouiColorWarning is shaded drastically for applying to text) are subject to updates based on initial results and will be reflected within this issue as needed
- There are some unknown visual impacts on components - for example the focus colors for things like Accordion, which on click the color of the icon is transformed from the text color to the primary color 
- Included in these core definitions, some specific color definitions for some aliases in order to address potential contrast issues using the current shade/tint approach in OUI - as well as separating the color use of Primary from Link
- Do not use absolute white #FFF or absolute black #000 for _any_ elements within the styling update. Please update UX team via comments if those values remain within the code after these updates and we will work on their appropriate replacement. 

**LIGHT MODE**
ouiColorEmptyShade #FCFEFF
ouiColorLIghtestShade #E3E5E8
ouiColorLightShade #D6D9DD
ouiColorMediumShade #ADB4BA 
ouiColorDarkShade #5A6875
ouiColorDarkestShade #2A3947
ouiColorFullShade #0A1219 
ouiColorPrimary #159D8D
ouiColorSecondary #017D73
ouiColorAccent #DD0A73
ouiColorWarning #F5A700
ouiColorDanger #BD271E
ouiLinkColor #006BB4
ouiPageBackgroundColor #F0F2F4
ouiColorInk #0A121A
ouiColorGhost #FCFEFF 

**DARK MODE**
ouiColorEmptyShade #0A121A
ouiColorLIghtestShade #101B25
ouiColorLightShade #293847
ouiColorMediumShade #5B6875
ouiColorDarkShade #8D98A3
ouiColorDarkestShade #DFE3E8
ouiColorFullShade #FCFEFF
ouiColorPrimary #159D8D
ouiColorSecondary #7DE2D1
ouiColorAccent #F990C0
ouiColorWarning #FFCE7A
ouiColorDanger #FF6666
ouiLinkColor #1BA9F5
ouiPageBackgroundColor #172430
ouiColorInk #0A121A
ouiColorGhost #FCFEFF

**VIS COLORS**
Tracked in another issue https://github.com/opensearch-project/oui/issues/818
Utilize OUI color palettes for iterative improvements https://oui.opensearch.org/1.2/#/utilities/color-palettes
- related task - point OSD to use OUI visualization palettes for visual & accessibility testing

**TYPOGRAPHY**
_Font sizing may need to be adjusted based on initial results._
ouiFont - [Source Sans 3](https://fonts.google.com/specimen/Source+Sans+3)
ouiCodeFont -[ Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro)

**Comment by BSFishy** [comment]
According to the code, `ouiColorInk` and `ouiColorGhost` must stay at `#000` and `#FFF`. If I'm not mistaken, the reason is that these colors are used when shading or tinting other colors. I.e. they're used in the functions to make other colors lighter or darker. I'm thinking changing these might have unexpected impacts on colors but haven't tested

**Comment by KrooshalUX** [comment]
@BSFishy Our contrast ratios for the new color scheme are not based on absolute black or white - we are trying to move away from those values for text especially. So, keeping those black and white may provide the wrong automatic adjustments to the colors provided. So, I would like us to try to implement this change and see what happens, we can adjust if the shades and tints end up funky.

**Comment by KrooshalUX** [comment]
Based on initial screenshots, I think this is going the right direction! 

![Screenshot (64)](https://github.com/opensearch-project/oui/assets/105819041/85558fde-f9e1-4a69-857a-1fed02ef0309)
![Screenshot (63)](https://github.com/opensearch-project/oui/assets/105819041/d0d676c2-d2b1-4061-adf3-6ebe3d52a696)
![Screenshot (60)](https://github.com/opensearch-project/oui/assets/105819041/75aba1c9-7adc-46d1-8294-e378640bdeb9)
![Screenshot (59)](https://github.com/opensearch-project/oui/assets/105819041/a53d02ef-15af-46c9-b55e-264308fc5f2e)


@BSFishy  curious to know if any of the supplied values were transformed after the compiling? It would be good for us to check those before moving forward on further changes. 

@kgcreative I am thinking that ouiLInkColor should actually just point to Primary afterall, as the mix of Button and Link colors is kind of frustrating on my eye - also, since we have little control over how/when builders will use links vs button for navigation, this reduces visual impact. I think we might need to adjust our Primary _slightly_ - but I would like to make that judgement once we have an endpoint vs screengrabs that may be altering colors during compression.

**Comment by BSFishy** [comment]
> @BSFishy curious to know if any of the supplied values were transformed after the compiling? It would be good for us to check those before moving forward on further changes.

Diff of light theme: https://gist.github.com/BSFishy/cdfde4221bdaefb7276f47f07ef206f3
Diff of dark theme: https://gist.github.com/BSFishy/4cbc1faa641e5610aad8344744bee28d

**Comment by KrooshalUX** [comment]
Round 2 style change:  Remove my original suggestion to use a specific ouiLinkColor and allow it to point to Primary as the default.

**Comment by AMoo-Miki** [comment]
Parts of OUI that don't honor the fonts set in SASS vars:
* `OuiText > blockquote`
* Anything using Ace or Monaco

**Comment by AMoo-Miki** [comment]
> Breadcrumb isn't using ouiColorPimary

> The font looks a bit blurry in breadcrumb

Breadcrumbs are `ouiLink`s and use `color` prop of `text` or `subdued`. `text` uses `$ouiColorGhost` and `subdued` uses `$ouiTextSubduedColor`. Would you want us to override the `text` only inside breadcrumbs to `$ouiColorPimary`?

On a side note: a crumb with `:focus` shows am odd colored background that is not shaped as the crumb.

**Comment by AMoo-Miki** [comment]
> OuiSuperUpdateButton text is perhaps being overridden still 

Yes there is some rouge styling in a plugin: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/509

**Comment by AMoo-Miki** [comment]
> Change ouiText letter spacing to 0, currently it is set at -.005em

The `letter-spacing` is applied by a mixin named `ouiFont` and has a wide reach. Would you prefer:
1. I simply set it to `0` for `ouiText`, or
2. remove the `-.005em` altogether?

**Comment by KrooshalUX** [comment]
> > Change ouiText letter spacing to 0, currently it is set at -.005em
> 
> The `letter-spacing` is applied by a mixin named `ouiFont` and has a wide reach. Would you prefer:
> 
>     1. I simply set it to `0` for `ouiText`, or
> 
>     2. remove the `-.005em` altogether?

@AMoo-Miki whatever makes the most sense for engineering ergonomics / code cleanliness from your perspective.

**Comment by AMoo-Miki** [comment]
> I would like to try a version where ouiButton font weight is bumped up to semi-bold

The weight now is 400. I have changed this to 600 which is what SemiBold is mapped to. FYI, we have a Medium too which is 500.

**Comment by AMoo-Miki** [comment]
> if removing it all together impacts OuiTitle, then we should just set it to 0 specifically for OuiText.

`OuiTitle` had its own `letter-spacing` except for `xxs` and `xxxs`. I dropped `letter-spacing` from `ouiFont` and added the same to `xxs` and `xxxs` of `OuiTitle`.

**Comment by AMoo-Miki** [comment]
@KrooshalUX, `.osdWelcomeView` sets the background of the page when the OpenSearch logo spinner is shown. It has a hardcoded background color which differs from those of OSD itself.
```
background-color: ${darkMode ? '#1D1E24' : '#FFF'};
```

Would you rather we use the default background color on this?

**Comment by KrooshalUX** [comment]
The first pass of color implementation has gone live, so closing this as completed. We will be tracking follow up tasks for improvements in a new issue.
