### ISSUE TITLE
Remove "Emphasized side nav sections" guidance from OUI Docs Site

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#824]
OpenSearch Design System does not encourage or support the use of emphasized side nav sections, and to reduce confusion with builders and designers alike, I would like to remove this example from the documentation website. 

![Screen Shot 2023-06-19 at 5 11 45 PM](https://github.com/opensearch-project/oui/assets/105819041/a2d267e4-8109-44ad-bbb2-52bcf938b8aa)

**Comment by Willie-The-Lord** [comment]
Hi @joshuarrrr, I would like to work on this issue.
