### ISSUE TITLE
[BUG] Fix lint issue in precommit hook

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/oui#83]
**Describe the bug**

Lint failure in precommit hook, doesn't give proper instructions on how to solve. This is sometime blocking developers to commit or sometime forcing developers to push commit with ` --no-verify` flag which is not advisable.

**Comment by bandinib-amzn** [comment]
Pre-commit hook is running yarn lint to check lint errors and running unit test for staged files to make sure your change is not breaking anything. I think we need both to make sure quality of the code.

I think instead of removing or relaxing checks on pre-commit, we should write clearly on document what to do in case of lint failure while committing.

**Comment by BSFishy** [comment]
This is an issue because `sass-lint` uses formatters that used to be in `eslint` to format errors. `eslint` has since removed those formatters, so whenever `sass-lint` has an error, it doesn't have a formatter to display that error. This will be resolved when we switch to Stylelint tracked in #119

**Comment by BSFishy** [comment]
No lint issue is currently occurring, and a migration strategy has been outlined
