### ISSUE TITLE
(OUI Docs) Remove all elastic references from .md files

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#86]
- [x] #104
- [x] #103
- [x] (OUI Docs) wiki/automated-accessibility-testing.md
- [ ] (OUI Docs) wiki/component-development.md
- [ ] (OUI Docs) wiki/consuming.md
- [ ] (OUI Docs) wiki/creating-components-manually.md
- [ ] (OUI Docs) wiki/creating-icons.md
- [ ] (OUI Docs) wiki/documentation-guidelines.md
- [x] (OUI Docs) wiki/react-router.md
- [ ] (OUI Docs) wiki/releasing-versions.md
- [ ] (OUI Docs) wiki/theming.md

**Comment by manasvinibs** [comment]
Closing as both the issues tagged to this has been merged.

**Comment by joshuarrrr** [comment]
Reopening for some additional docs to clean up.
