### ISSUE TITLE
(OUI Docs) Writing Guidelines

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#87]
- [x] Remove page - this will be moved out of OUI and into the OpenSearch Design System guidance documentation website.

**Comment by KrooshalUX** [comment]
Blocking this issue for now, since at this point we are getting so close to our editorial redesign collaboration that we might just want to focus on the edits that come out of those prescribed changes.

**Comment by manasvinibs** [comment]
Closing https://github.com/opensearch-project/oui/pull/503
