### ISSUE TITLE
[BUG] In dark mode, auto-populated fields are tough to see

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/oui#870]
**Describe the bug**

Input fields that are auto-populated by the browser, like a saved usernames, are too dark to see in the dark mode for both default and Next themes. That is because the "shades" are reversed in dark mode where `$ouiColorLightestShade` is in fact nearly black and `$ouiColorDarkestShade` is nearly while. The code below wrongly uses `$ouiColorLightShade`, which is a dark color, on a dark background. 

https://github.com/opensearch-project/oui/blob/0365b429fd7935ef8b8e5b31f232c4e6a73c67e1/src/themes/oui-next/global_styling/mixins/_form.scss#L265-L277

`$ouiColorDarkestShade` or `$ouiColorDarkShade` are much more suitable for the dark themes input-fields.

**Screenshots**

<img width="343" src="https://github.com/opensearch-project/oui/assets/3527403/4b813f07-ba64-44ad-b628-d1e513c0e310">

<img width="334" alt="Screenshot 2023-06-30 at 8 40 41 PM" src="https://github.com/opensearch-project/oui/assets/3527403/d5f4c713-2bf6-446e-9a4d-c92a1d1e23e6">

**Comment by KrooshalUX** [comment]
I have new values that need to be implemented but was waiting for endpoint to return to verify. I'll be adding the correct values to the original issue.
