### ISSUE TITLE
(OUI Icons)(Meta) Icons for OSD 2.10 Release 

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#873]
The following icons need to be added the OUI icon library as well as the OUI documentation website. 

- [x] #875
- [x] #876
- [x] #877
- [x] #878

This task will become unblocked when all sub-issues are completed and icon asset files are delivered to engineering.

**Comment by KrooshalUX** [comment]
@canascar  please upload a .zip of all the icon assets for this release. The names should match the namespaces given in each of the issues. 

@joshuarrrr @BSFishy @AMoo-Miki once this .zip is uploaded, these icons can be added to OUI.

**Comment by canascar** [comment]
@KrooshalUX, @joshuarrrr, @BSFishy, @AMoo-Miki - All icons in this repo added in the zip file below (Raw and compressed versions) @kgcreative 
[OUI Icons (Meta).zip](https://github.com/opensearch-project/oui/files/12488678/OUI.Icons.Meta.zip)

**Comment by AMoo-Miki** [comment]
Thanks. Got the zip with 2 icons: redeploy and undeploy.
