### ISSUE TITLE
(OUI Icons) New - Chat Interactions

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#875]
- [ ] chatRight
- [ ] chatLeft
- [ ] thumbsUp
- [ ] thumbsDown

**Comment by canascar** [comment]
<img width="659" alt="Screenshot 2023-07-13 at 11 17 08 AM" src="https://github.com/opensearch-project/oui/assets/111922174/1747b8d0-1cab-4e18-99ef-2c89c8b0a783">

Zip file contains Chat Integration set of Raw/Compressed formats:
[Chat interactions.zip](https://github.com/opensearch-project/oui/files/12042973/Chat.interactions.zip)

**Comment by KrooshalUX** [comment]
@canascar approved for review with stakeholders

**Comment by KrooshalUX** [comment]
LGTM
