### ISSUE TITLE
(OUI Icons) New - Undeploy & Deploy

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#876]
- [ ] deploy
- [ ] undeploy

**Comment by canascar** [comment]
For review: 
<img width="873" alt="Screenshot 2023-07-31 at 9 43 51 AM" src="https://github.com/opensearch-project/oui/assets/111922174/3b80c27b-e720-4141-b21e-a3e95bc24cde">

4 versions - select direction and will prepare SVG files for development.

**Comment by KrooshalUX** [comment]
@canascar lets iterate on V1 - lets explore the icons on the plane

**Comment by canascar** [comment]
@KrooshalUX Deployment updates:
1. On the plane
<img width="1057" alt="Screenshot 2023-08-29 at 1 15 52 PM" src="https://github.com/opensearch-project/oui/assets/111922174/8450ea90-b98a-4bc4-89de-0968ae240490">

2. Package deployment with extras (Delpy Success/Deploy(ed), deployFailed: 
<img width="1055" alt="Screenshot 2023-08-29 at 1 13 30 PM" src="https://github.com/opensearch-project/oui/assets/111922174/15f1321c-4530-4f89-a475-9eba211b38b7">

**Comment by KrooshalUX** [comment]
I like the ideas of the package, but the symbols are too thick. Lets stick with version 1, on the plane.

**Comment by canascar** [comment]
@KrooshalUX quick review:
1.Smaller (x)
2. Bigger gap

<img width="778" alt="Screenshot 2023-08-30 at 1 24 16 PM" src="https://github.com/opensearch-project/oui/assets/111922174/197a906c-bafd-4e06-a7b2-7acb2e838c2d">

**Comment by canascar** [comment]
@KrooshalUX 

<img width="91" alt="Screenshot 2023-08-30 at 1 38 20 PM" src="https://github.com/opensearch-project/oui/assets/111922174/5d22990d-1af0-4094-a314-da405065b8a9">

**Comment by KrooshalUX** [comment]
@canascar bottom one with bigger x is the way to go for now. Thanks for the iterations !

**Comment by canascar** [comment]
Ready for implementation @KrooshalUX 
1. redeploy
2. undeploy

[redeploy-undeploy.zip](https://github.com/opensearch-project/oui/files/12480489/redeploy-undeploy.zip)

**Comment by canascar** [comment]
Yes, this may be closed- thanks @joshuarrrr
