### ISSUE TITLE
(OUI Icons) New - Integrations fall-back

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#877]
When an integration has been submitted without a logo, or there is an error in the logo file, the application should render a fall-back placeholder icon. 

There are currently 3 planned categories for integrations, however we should also supply a generic icon for "integration" - and use that as the base for communicating the categories (this way in the event where logo images are not loaded the integrations grid does not become a sea of identical icons). 

- [ ] Integrations
- [ ] Search analytics
- [ ] Search
- [ ] Observability

**Comment by canascar** [comment]
<img width="629" alt="Screenshot 2023-07-12 at 3 02 02 PM" src="https://github.com/opensearch-project/oui/assets/111922174/16fb491e-5c46-4d85-92cd-2183ef096fb0">

Zip file contains all four Raw/Compressed formats:
[Integrations.zip](https://github.com/opensearch-project/oui/files/12042776/Integrations.zip)

**Comment by KrooshalUX** [comment]
@canascar  adjust center icons for spacing between arrows and icon.

**Comment by canascar** [comment]
Centered and refined @KrooshalUX :
<img width="761" alt="Screenshot 2023-08-10 at 2 57 02 PM" src="https://github.com/opensearch-project/oui/assets/111922174/fc453b4b-e4a4-43aa-a6d1-2cbdf15e7f33">

**Comment by KrooshalUX** [comment]
@canascar these look better. do you mind posting the icons at a small size? i would like to see how the search and shield sit

**Comment by canascar** [comment]
@KrooshalUX smaller sizes for review:
<img width="129" alt="Screenshot 2023-08-17 at 1 32 22 PM" src="https://github.com/opensearch-project/oui/assets/111922174/e1fef0e1-564b-4a23-b9f6-1ea6c094d2ce">

**Comment by canascar** [comment]
@ kavck, @brijos Please review upcoming icons for integration categories

**Comment by canascar** [comment]
@KrooshalUX integrations SVG (raw/compressed) ready for hand-off:
[Integrations.zip](https://github.com/opensearch-project/oui/files/12432108/Integrations.zip)

**Comment by KrooshalUX** [comment]
LGTM.
