### ISSUE TITLE
(OUI Icons) New - checkInCircileEmpty

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#878]
In addition to check, and checkInCircleFilled, we would like to add a non-filled version in a circle for check. This way icon can appear to "toggle" in some cases, and also be able to provide a balance in the UI where filled icons are somewhat rare.

**Comment by canascar** [comment]
<img width="411" alt="Screenshot 2023-07-12 at 3 40 49 PM" src="https://github.com/opensearch-project/oui/assets/111922174/1f25e712-8529-42be-a557-b3986014acf5">

[circleCheck.zip](https://github.com/opensearch-project/oui/files/12042570/circleCheck.zip)

**Comment by KrooshalUX** [comment]
Approved!
