### ISSUE TITLE
(OUI Docs) Notification event 

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#88]
- [ ] remove all logos from each example
- [ ] remove "beta" from page
- [ ] remove "new" from side navigation

**Comment by bandinib-amzn** [comment]
@KrooshalUX 

Evaluate Notification event in its current state from the above list - Is it auditing task for notification event?

**Comment by kavilla** [comment]
@kaddy645 will look into this.

**Comment by kaddy645** [comment]
@KrooshalUX I do not think we are using this component anywhere in OSD. looking at its current state it looks good to use. In future we might need to update some of its prop if needed.

**Comment by KrooshalUX** [comment]
@kaddy645  correct, we are not using it yet. I mostly just wanted to know if there is anything you might find that would prevent us from using it - sounds like no concern with its current implementation and documentation. Thanks!

**Comment by KrooshalUX** [comment]
@kaddy645 did you notice any differences between the component and the documentation? if not, we can check these tasks off and close the issue, and i can remove beta from the docs pages (tracked in the meta docs issue)

**Comment by kaddy645** [comment]
Component looks good to me. there are few required props we have in docs that end user will need when using this component. 

* **Id** : A unique identifier title :The title of the event.
* **eventName** : A unique, human-friendly name for the event to be used in aria attributes (e.g. "alert-critical-01", "cloud-no-severity-12", etc..
* **messages** : Notification messages as an array of strings. More than one message wraps in an accordion.
* **time** : Indicates when the event was received.
* **iconType** : icon used to visually represent this data type. Accepts any OuiIcon IconType.
* **type** : Type of event (e.g. "Alert", "Cloud", etc..). Shows inside a badge.

**Comment by KrooshalUX** [comment]
Updated description relevant to docs site task
