### ISSUE TITLE
OuiCallOut - Add props to enable dismissible behavior

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#880]
DRAFT WIP 

Currently OuiCallOut provides builders a way to communicate relevant information to a users experience in relationship to a page or flow, however, in some cases the information does not always need to persist, but utilizing OuiToast is not appropriate (feature announcements, for example). 

In order to give vital real-estate back to the end user, it is appropriate to allow builders to configure if a call-out should be static or dismissible by the end user. 

- All existing props should remain in-tact
- `dismissible` can be set to `TRUE` or `FALSE` except in the case where `color` is set to `danger` or `warning` (`danger` is used in Form validation and is [required by the design system to appear statically](#885 )
- Default value of `dismissilbe` is `FALSE`, as dismissible is a sub-variant of the base component
- When `dismissible` is set to `TRUE`, `OuiIcon type=cross` should appear in upper right hand corner of OuiCallOut
- `OnClick` of `OuiIcon type=cross` - OuiCallOut should disappear from the page without causing page refresh
- After a callout is dismissed, it should not reappear
      - Is this a property of the component or a property of the implementation by builders (and therefore this requirement would be associated with a dashboards issue to implement OuiCallOut ex: Notifying users of how to override [Dark Mode by Default](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4454))? 
      - Since there is no User object, this may be limited to session or device

Designs (primary, hover)

Notes: This dismissible variation of `OuiCallOut` (or any `OuiCallOut`) is not intended to display confirmations of user CRUD actions - for that, builders should continue to use `OuiToast`. This and other guidance will be explicitly updated on within https://github.com/opensearch-project/oui/issues/883.

**Comment by KrooshalUX** [comment]
After initial review with @kgcreative  we are going to pause on `dismissable`in favor of `collapsable` #882

**Comment by abbyhu2000** [comment]
For the `OnClick` function of `OuiIcon type=cross`, is it beneficial to make the function itself also a prop so user can configure what type of function they want after clicking the cross when using `OuiCallout`? 

I see `OuiModal` have similar design, where they pass in `onClose` function as one of its props. @KrooshalUX @ashwin-pc

**Comment by ashwin-pc** [comment]
So the showing and hiding of a modal is controlled by the user, so the onClose is important in that flow. For the call out, I think a more opinionated flow where the user can only specify if the model is dismissible, but does not have a say in how to do it. We can always expand this in future by allowing an onClose function to override the default. But I don't think we need to complicate that for now. @KrooshalUX what do you think?

**Comment by KrooshalUX** [comment]
Closed with https://github.com/opensearch-project/oui/pull/985
