### ISSUE TITLE
Remove Internet Explorer specific code 

### ISSUE THREAD

**Issue by gulderov** [opensearch-project/oui#886]
Internet Explorer has officially retired and out of support. Given that our `.browserslistrc` is already set to `not dead`. It is not longer necessary to include Internet Explorer specific code in codebase

As per [Browserslist documentation](https://browsersl.ist/#q=dead) IE considered 'dead'

Here are the proposed changes:

* Clean IE from `.browserslistrc` file 
* Remove browser specific checks like `isIE`, `documentMode`, `MSInpiutMethodContext`

**Comment by joshuarrrr** [comment]
Thanks @gulderov, that seems like a good idea - are you interested in raising the PR for this change?

**Comment by gulderov** [comment]
I would be happy to create a pull request to resolve this issue
