### ISSUE TITLE
Update OuiHeader background to use the same value as OuiPageBackgroundColor

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#901]

**Comment by joshuarrrr** [comment]
@KrooshalUX Currently the `OuiHeader` takes a `theme` prop which can be set to dark, and there's a different background color defined in that case: 

https://github.com/opensearch-project/oui/assets/1679762/e32a7c55-cdd6-42e3-a53e-0c6518a2388e

https://github.com/opensearch-project/oui/blob/f718f63ae058788b3a31d1aea6dfbee649c2275c/src/global_styling/variables/_header.scss#L12-L16

**Comment by joshuarrrr** [comment]
The actual values:

Next dark:
```
 "ouiHeaderBackgroundColor": "#0a121a",
  "ouiHeaderDarkBackgroundColor": "#0d1720",
```

Next:
```
"ouiHeaderBackgroundColor": "#fcfeff",
  "ouiHeaderDarkBackgroundColor": "#212e3a",
```

**Comment by KrooshalUX** [comment]
"So what should we do for when the dark header prop is set (in both light and dark site themes?)" - good question. 

The idea behind using the background page color as the navigation background color is to help the page content "pop" and give a lighter, less chrome-heavy feeling to the application (there is more to do in this regard, like perhaps removing the bottom border, but thats TBD after seeing the result of this change IRL). 

So, in that lens - my overall concern is regarding the defaults - less so decisions the dashboards customer/builder may have chosen (ex: dark mode navigation in a light mode interface). I imagine deprecating this at this phase will cause unexpected chaos, so for users/customers/builders who have manually set this, if they are using light mode but set the header to dark mode, it wont have the same appearance effect, but at least it would reflect the correct color (vs what appears to be a much darker color than I intended).
