### ISSUE TITLE
Increase brightness of click /focus highlight across components

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#906]
**Current theme examples:**
<img width="116" alt="Screen Shot 2023-08-07 at 1 42 50 PM" src="https://github.com/opensearch-project/oui/assets/105819041/bbc9cf71-919a-4f94-9a48-5ae9a93ebbc9">
<img width="90" alt="Screen Shot 2023-08-07 at 1 44 18 PM" src="https://github.com/opensearch-project/oui/assets/105819041/c2e6fd71-4a85-445e-9d78-1ac506af4ed8">

**Next theme:**
<img width="110" alt="Screen Shot 2023-08-07 at 1 43 02 PM" src="https://github.com/opensearch-project/oui/assets/105819041/687ca010-27f2-4332-a490-03c22b89ee0a">
<img width="103" alt="Screen Shot 2023-08-07 at 1 43 33 PM" src="https://github.com/opensearch-project/oui/assets/105819041/235ce617-a1d8-4084-bfb3-83fe101e2278">

**Comment by joshuarrrr** [comment]
@KrooshalUX Do you mind adding screenshots when you get a chance here? I think I remember the issue, but I want to make sure we fix the right thing.

**Comment by KrooshalUX** [comment]
@joshuarrrr  updated with examples from discover. SEeing them side-by-side, this may be OK. The dark mode on both current and next are equally dull and blend in with their respective backgrounds, so we may want to address the overall way this is implemented?

**Comment by BSFishy** [comment]
Should be done with #948
