### ISSUE TITLE
OuiSchemaListItem  & OuiSchemaList

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#908]
This component provides solutions for interactive lists of data fields within OpenSearch Dashboard features & applications. These changes support efforts for creating a cohesive visual and interactive experience across Discover, VisBuilder, Observability Logs and Observability Metrics interfaces. The component can be clickable, or used within the OuiDraggable wrapper. 

**Examples of disjointed interactive data fields list patterns within Dashboards:**

![image](https://github.com/opensearch-project/oui/assets/105819041/070118d2-b708-44e4-91cd-3a606aa272aa)

**Zoning of OUISchemaListItem**
<img width="910" alt="Screen Shot 2023-07-27 at 10 49 52 PM" src="https://github.com/opensearch-project/oui/assets/105819041/93a6007a-1c0b-4489-95c9-6758abf3d00d">

**Label**
- Label should wrap, not truncate. This resolves issues with displaying lists of data (fields, attributes, metrics, etc) 

*SchemaActions*
- Allow a primary action & primary action icon. Primary action is aligned to the right. Primary action should be styled by default using OuiColorPrimary
      - An example of a primary action is "Add" - which on click would add the data to a targeted list (this is also a backup option for drag and drop interactions) 
      - When using keyboard navigation / tabbing , Primary action should be in focus after the panel focus. 

- Allow a secondary action & secondary action icon (up to 2). Secondary actions align left of the primary actions. Secondary actions should be styled using OuiColor
      - An example of a secondary action is "Override default pattern" (as seen in Observability logs) or "Show top 5 values" (as seen in Discover).
      - Secondary actions receive tab focus after primary actions, starting from the right

- Show button group on hover - boolean (True/false) - default to true. when true, only show actions on hover. when false, always display actions button group. The preferred default is true. 
- Button groups should be shown on keyboard focus. This interaction can be seen in Discover when tabbing through the data fields list.  

**OuiPanel**
- SchemaListItem can be displayed with or without OuiPanel background. Display SchemaItem on a panel by default. 
- Allow builders to choose styled or unstyled panel (padding and panel sizing informed by `OuiDraggable`) as well as compressed options.

**OuiSchemaList**

**Examples:**
![image](https://github.com/opensearch-project/oui/assets/105819041/4606f709-df1d-41c9-95de-7e52ee8b5ff3)

**Comment by pjfitzgibbons** [comment]
Love this!

For button-group show -- I'm confused between "onHover, Default Action - False" and "Show button group onHover - False"?

Is there a combination of attributes that switch between showing "this-facet's" action-group and showing "all facets" action-groups when any one of them is hovered?

**Comment by KrooshalUX** [comment]
@pjfitzgibbons we are removing Default Action to simplify focus as we are running into collisions between the draggable and clickable areas. I will have updated mocks shortly that hopefully clarify further.

**Comment by ashwin-pc** [comment]
Here are some other names you can consider:
1. OuiDataField
2. OuiFieldItem
3. OuiField

Their group counterparts can be:
1. OuiDatagroup
2. OuiFieldGroup
3. OuiFieldGroup

**Comment by pjfitzgibbons** [comment]
Naming : 
We started out with OuiFacet, which is a fine, abstract name.   I feel that 'field' and 'data' carry too much meaning for a widget that we intent to have abstract use-case.  'field' is especially specific.  I could be convinced that 'data' is ok, though I have strong opinion, weakly held.

Without the advantage of knowing wider OUI plans and UX Design tenets, I don't see a problem in calling this an extension of OuiFacet ?

**Comment by pjfitzgibbons** [comment]
Alternately :  IF this is a specific widget, with a specific use-case (Schema type configuration, a-la vis-builder), then the OuiSchemaItem name works just fine.  The widget will be unlikely to be used in any other context with the proposed name OuiSchemaItem.

**Comment by KrooshalUX** [comment]
We have pivoted away from this being an extension of OuiFacet because it was leading to interaction collisions when included in certain wrappers.

@ashwin-pc 'field' is used in all of our form control components - but perhaps we can riff on the 'data' suggestion. I'm OK keeping it 'schema' as well.

**Comment by KrooshalUX** [comment]
@ashwin-pc I've updated the styling approach to include `compressed` options for both on panel and off panel.

**Comment by pjfitzgibbons** [comment]
I'm feeling that using within drag/drop disables default-link is an OK compromise.   Might require very specific documentation so an user-developer understands that default-link is disabled in the drag/drop scenario.

**Comment by KrooshalUX** [comment]
@pjfitzgibbons in our latest explorations we have gotten rid of Default Action behavior to avoid these issues further.
