### ISSUE TITLE
(OUI Next Theme) Visualize - TSVB

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/oui#913]
_This issue to be transferred to corresponding repository_

I am working on launching new light and dark mode themes provided by [OUI component library](https://oui.opensearch.org/1.2/#/) for a target launch within 2.10. These changes support the vision expressed in [Future Vision for Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298.)

I have identified the following front end related issues that prevent the theme from appearing complete and potential solutions within this feature:

- [x] While in dark mode, editor appears in light mode

**Comment by joshuarrrr** [comment]
Fixed via https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4609
