### ISSUE TITLE
(OUI Next Theme) Dashboards - Data Plugin

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#917]
_This issue to be transferred to corresponding repository_

I am working on launching new light and dark mode themes provided by [OUI component library](https://oui.opensearch.org/1.2/#/) for a target launch within 2.10. These changes support the vision expressed in [Future Vision for Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298.)

I have identified the following front end related issues that prevent the theme from appearing complete and potential solutions within this feature:

- [x] While in dark mode, OpenSearch Query DSL editor appears in light mode color theme
<img width="660" alt="Screen Shot 2023-07-25 at 3 22 38 PM" src="https://github.com/opensearch-project/oui/assets/105819041/5bc62233-89dc-4afc-b15b-4eb596e709c6">

- [ ] Search bar - bottom border missing, appears blurry & text appears lower than in `Current` theme
<img width="670" alt="Screen Shot 2023-07-25 at 3 23 58 PM" src="https://github.com/opensearch-project/oui/assets/105819041/356e78ea-c9b2-4fd7-accb-eee20c30d50a">

**Comment by joshuarrrr** [comment]
> While in dark mode, OpenSearch Query DSL editor appears in light mode color theme

fixed via https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4609

**Comment by joshuarrrr** [comment]
> Search bar - bottom border missing, appears blurry & text appears lower than in Current theme

This is not currently an issue. We can reopen if we decide to go forward with the global font size adjustment in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4456
