### ISSUE TITLE
(Oui Docs) Code Editor

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#92]
`OuiCodeEditor` was marked for deprecation by Elastic in 34.6 - however it had not yet been removed at the time of the fork, so I believe we are still able to utilize it.  It is still in use on Dashboards, and it is still a useful component for our efforts on new projects. 

Ideally , we should restore a previous version of the documentation rather than surfacing the deprecation notice. 

- [ ] Identify if there is a way to access previous versions of the documentation 
- [ ] If unable to restore previous version, document implementation details for Code Editor & work with UX on a new page for Code Editor

**Comment by kavilla** [comment]
@kaddy645 will be working on this.

**Comment by BSFishy** [comment]
The doc change to deprecation happened in commit https://github.com/opensearch-project/oui/commit/f7e07ac964309c24b4d049b166193ffbb81b5bd4. We could roll that back but would still need to verify its accuracy.

**Comment by AMoo-Miki** [comment]
Why not continue to deprecate `OuiCodeEditor` and either pull in `@osd/monaco` or just not have a replacement?

**Comment by KrooshalUX** [comment]
@AMoo-Miki  @ashwin-pc  can you provide some information / documentation about `@osd/monaco` ? I was not aware that we had a different code editor in place on dashboards. 

Since monaco is already being used and there are +1s on adoption, I don't object to deprecating `OuiCodeEditor` in favor of `@osd/monaco". We will need to come up with a roadmap for deprecating `OuiCodeEditor` that includes notifying OSD & plugins, as well as creating a monaco component and its accompanying documentation.

**Comment by ashwin-pc** [comment]
`@osd/monaco` is a customized version of monaco that is automatically configured for OSD.
- https://microsoft.github.io/monaco-editor/
- https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-monaco/README.md

The main customization seems to be how it adds xjson language support.
Given that `@osd/monaco` uses a very old version of the monaco editor, it might be easier to just build the new CodeEditor from scratch and port over these customizations from `@osd/monaco`

**Comment by KrooshalUX** [comment]
Closing this as wont change content for the release of OUI Docs 1.0. Additional issues are coming for the component replacement planning.
