### ISSUE TITLE
Enhance OUIBetaBadge for experimental releases 

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#93]
- [ ] Change "Beta" to "Experimental" 
<img width="935" alt="Screen Shot 2022-10-21 at 11 50 14 AM" src="https://user-images.githubusercontent.com/105819041/197268562-4d9a9c9e-19ad-4da3-8fa5-670a1e4a2c2d.png">

- [ ] Change label inside tooltip to "experimental" 

- [ ] Remove option for "E" 

- [x] Remove styling option "accent"
- [x] Identify how introduce the name OuiExperimentalBadge and if OuiBetaBadge and OuiExperimentalBadge can be used interchangeably

**Comment by kgcreative** [comment]
I really like this for Experimental features. I'm not opposed to keeping the `lab` icon to reinforce `experimental`

**Comment by kgcreative** [comment]
(In fact, i prefer it to `E` or `Exp`)

**Comment by KrooshalUX** [comment]
@kgcreative  the idea is to enhance this for Experimental so we can use the lab or "beaker" icon on small components (like tables cells). I have given guidance in https://github.com/opensearch-project/ux/issues/49 to replace the "E" with `OuiBadge` using beaker icon.

**Comment by KrooshalUX** [comment]
@kaddy645  can you weigh in on the last to-do of this list about naming?

**Comment by BSFishy** [comment]
For the last item, I don't think we need a completely separate component. The beta badge currently expects a `label` property, which can be easily changed to say `experimental`. I suppose we could make a separate component and have the `OuiBetaBadge` component default to label being `Beta` and `OuiExperimentalBadge` default to label being `Experimental`, but that seems very redundant to me.

![2022-10-28 12_05_13-Badge - OpenSearch UI Framework](https://user-images.githubusercontent.com/6763209/198713482-36149174-5b32-4f56-ae3d-1fd6b3e5fd26.png)

**Comment by KrooshalUX** [comment]
@BSFishy the last item has to do with aliasing and implementation. We do it want designers or builders using "beta", we want them to use experimental. That is why I want to make the change to the component itself vs relying on the implementer to change beta to experimental (different task item). For naming right now OSD can call EuiBetaBadge which will then actually call OuiBetaBadge - but since we want to move away from "Beta" language we need to either map EuiBetaBadge to OuiExperimentalBadge or allow EuiBetaBadge to be called which points to OuiBetaBadge which contains the changes as well and allow OuiExperimentalBadge to be called when OUI is used directly.

**Comment by KrooshalUX** [comment]
We need to decide on how we want to go about releasing these changes before everything gets merged, correct? I am good with the plan to introduce OuiExperimentalBadge and deprecate OuiBetaBadge, but not sure what is involved in that process. Can someone please outline next steps? @AMoo-Miki  @BSFishy  @kaddy645 ?

**Comment by BSFishy** [comment]
> We need to decide on how we want to go about releasing these changes before everything gets merged, correct?

Yes, some of these changes are potentially breaking, warranting a major version bump.

1. Change "Beta" to "Experimental" text in docs should be fine. That isn't a user-facing change.
2. Removing the "accent" color option is a breaking change. We could just leave the PR open until we're ready for a major version bump.
3. Introducing `OuiExperimentalBadge` and deprecating `OuiBetaBadge` **should** be a minor version bump. All I've done so far is rename all instances of `OuiBetaBadge` to `OuiExperimentalBadge` and rename some of the CSS classes, but it seems that `OuiBetaBadge` stretches outside of that. It is unlikely that the changes are going to be breaking, but not out of the picture.

Here's how I think versions will need to be bumped for these merges:

 - Doc change "Beta" to "Experimental": **No bump - no change to code**
 - Remove "accent" color option: **Major version bump - functionality removed**
 - Introduce `OuiExperimentalBadge`, deprecate `OuiBetaBadge`: **Minor version bump - interfaces added/updated (\*PROJECTED\*)**

@AMoo-Miki can confirm this and discuss how we can go about merging these for proper version bumping

**Comment by KrooshalUX** [comment]
@BSFishy One last change has occurred to me, we do not want to use the "E" abbreviated version, only "experimental" or the beaker version. So, we need to make an additional breaking change to remove that option as well.

**Comment by AMoo-Miki** [comment]
@BSFishy please don't remove the existing component in the 1.0; (1) create a new component, even if it is identical to the old one + name change, (2) mark the beta one deprecated and include it in the changelog as being deprecated.

When OUI 2 is being released, we would simply delete the beta one.

**Comment by KrooshalUX** [comment]
Closing in favor of issue #161
