### ISSUE TITLE
(OUI Docs) Badge

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#94]
Section: Badge groups and truncation
- [ ] Fix typo "only every be a single line of text" to "only ever be a single line of text" 

Section: Beta badge type

- [x] Replace with `OuiExperimentalBadge` content
- [ ] Replace beaker icon tooltips from "lab" to "experimental" 
- [ ] Replace "lab" with "experimental" in the line "beta badges will also line up nicely with titles"

Section - clickable beta badges: 
- [ ] Replace `lens` icon with visVisualBuilder
- [ ] Update tooltip on `lens` to Visualize
- [ ] Change URL on `lens` icon to https://playground.opensearch.org/app/visualize#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))
- [ ] Remove the modal that appears when clicking `lens`
- [ ] Update URL on "experimental" from elastic subscriptions to "https://opensearch.org/docs/latest/"

**Comment by BSFishy** [comment]
Beta badge alignment can be modified by changing the `vertical-align` property here:
https://github.com/opensearch-project/oui/blob/fa3d410e36e150d13043d55dba699395583a9995/src/components/badge/beta_badge/_beta_badge.scss#L17

I've found that a value of `text-bottom` aligns with titles better.

---

To include a tooltip in the "lab" type (I'm assuming this is referring to the beta badge with a beaker icon), the `tooltipContent` attribute needs to be included, as shown here:
https://github.com/opensearch-project/oui/blob/fa3d410e36e150d13043d55dba699395583a9995/src-docs/src/views/badge/beta_badge.js#L22-L26

Currently, the lab icons in the docs don't have that attribute, but it's a quick fix:
https://github.com/opensearch-project/oui/blob/fa3d410e36e150d13043d55dba699395583a9995/src-docs/src/views/badge/beta_badge.js#L39-L41

**Comment by BSFishy** [comment]
Additionally, the clickable beta badge that says `BASIC` currently links to an Elastic page, that we should change.

**Comment by KrooshalUX** [comment]
@BSFishy i have those changes accounted for in the docs page changes. I have separated the issues for docs and the actual component changes for tracking purposes.

**Comment by KrooshalUX** [comment]
@BSFishy yes, for clarity these tasks for docs are in addition to removing elastic references. The elastic reference task is tracked as a launch requirement. These are iterative, rolling changes.
