### ISSUE TITLE
(OUI Icons) New - Activate&Deactivate

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/oui#941]
**Is your feature request related to a problem? Please describe.**

For the objects that have active and inactive states (or modes) we need a way to indicate the state and to switch from one to another.

**Describe the solution you'd like**

Corresponding icons "activate" and "deactivate" will be the solution for the button icons on the object's page, action buttons in the tables and data grids, and indicators of the object status.

**Describe alternatives you've considered**

The alternatives we're currently exploring are:
- toggle switch (form element)
- OuiIcon: `play`, `playFilled`,` moon`, `pause`
**Additional context**
Inspiration:
<img width="122" alt="Screenshot 2023-07-31 at 1 04 09 PM" src="https://github.com/opensearch-project/oui/assets/105245012/0d940dd4-1f70-4d05-a8b6-b3762fbc0c4c">
<img width="253" alt="Screenshot 2023-07-31 at 1 05 43 PM" src="https://github.com/opensearch-project/oui/assets/105245012/c6630b16-2cb2-443e-aaa8-f5189fbbf111">

<img width="274" alt="Screenshot 2023-07-31 at 1 06 32 PM" src="https://github.com/opensearch-project/oui/assets/105245012/6b869e21-3897-4ff7-8870-fcd6d47fc275">
<img width="211" alt="Screenshot 2023-07-31 at 1 07 36 PM" src="https://github.com/opensearch-project/oui/assets/105245012/befc303f-df6c-4bb0-abaf-403a79effc62">

<img width="413" alt="Screenshot 2023-07-31 at 1 09 31 PM" src="https://github.com/opensearch-project/oui/assets/105245012/92146c00-874d-4c29-8410-f1a24555a2d6">

**Comment by KrooshalUX** [comment]
@xeniatup  @shanilpa the use of this icon would also apply to `OuiDataGrid` and `OuiBasicTable` rows, correct? If so, we could support a switch-like icon design _if_ those components could handle a "toggle button" like switch between icons (on click the icon state changes from switch-off to switch-on). 

We can explore this further from both iconography & iconography + row-actions appropriate treatment.

**Comment by xeniatup** [comment]
@KrooshalUX Yes, I forgot to mention that one status (or mode) will replace the other one. An active object can be deactivated, a deactivated object can be activated (or re-activated).

**Comment by canascar** [comment]
@KrooshalUX, @xeniatup, @kgcreative Activation icon ideas:

<img width="1345" alt="Screenshot 2023-08-30 at 10 39 12 AM" src="https://github.com/opensearch-project/oui/assets/111922174/d49f4080-0823-4445-913f-cd3448c59969">

**Comment by kgcreative** [comment]
A and B are the most unambiguous to me. @xeniatup -- do you have an example of how this would be used? Can you and carlos explore these in-context to make sure it works?
cc: @KrooshalUX

**Comment by xeniatup** [comment]
Here is an example for using the option F in a different context:
<img width="395" alt="Screenshot 2023-08-30 at 1 32 17 PM" src="https://github.com/opensearch-project/oui/assets/105245012/bf28d726-fa2d-4432-8859-9ec8fbfa0dd7">
<img width="395" alt="Screenshot 2023-08-30 at 1 33 44 PM" src="https://github.com/opensearch-project/oui/assets/105245012/0822533d-91bc-4b49-91d8-7995a43c810f">

**Comment by kgcreative** [comment]
@xeniatup -- Looks good to me! Let's go with Option F. @canascar, see xenia's feedback regarding the length of the vertical line.

**Comment by canascar** [comment]
@xeniatup, @KrooshalUX, @kgcreative:  
<img width="191" alt="Screenshot 2023-08-30 at 1 46 05 PM" src="https://github.com/opensearch-project/oui/assets/111922174/36476ada-771f-4b02-b16c-806d01bd7ab4">

**Comment by kgcreative** [comment]
@canascar Ship it!

**Comment by xeniatup** [comment]
@canascar The longer vertical looks great! Thanks!
<img width="568" alt="Screenshot 2023-08-30 at 1 57 26 PM" src="https://github.com/opensearch-project/oui/assets/105245012/676bc45e-9d5b-4e72-8426-311a69141b8f">

**Comment by canascar** [comment]
Ready for implementation @KrooshalUX :
2. power (activate)
1. crossInCircle (deactivate)
[crossInCircle-power.zip](https://github.com/opensearch-project/oui/files/12480484/crossInCircle-power.zip)

**Comment by kgcreative** [comment]
@joshuarrrr -> is this merged? if so, can we close this issue?

**Comment by joshuarrrr** [comment]
No - awaiting zip from @canascar

**Comment by joshuarrrr** [comment]
Also, for expediency, @canascar once you provide the final assets, just reassign to @BSFishy and me.

**Comment by canascar** [comment]
Activate icons ready @kgcreative, @BSFishy, @joshuarrrr: 
[Activate.zip](https://github.com/opensearch-project/oui/files/12653442/Activate.zip)

**Comment by BSFishy** [comment]
Completed in #1044
