### ISSUE TITLE
Release OUI 1.3

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/oui#958]
and update docs site

**Comment by joshuarrrr** [comment]
Should include https://github.com/opensearch-project/oui/issues/873 as well as many https://github.com/opensearch-project/oui/labels/next-theme issues.

**Comment by KrooshalUX** [comment]
@joshuarrrr  what is the targeted date for this release so I can coordinate with @canascar on wrapping up icons?

**Comment by joshuarrrr** [comment]
Realistically I'd be planning to do this on 9/1/2023

**Comment by ashwin-pc** [comment]
This needs to go in for 2.10 https://github.com/opensearch-project/oui/issues/908

**Comment by abbyhu2000** [comment]
This needs to go in for OSD 2.10 #985

**Comment by joshuarrrr** [comment]
completed via #1021 and https://github.com/opensearch-project/oui/issues/1022
