### ISSUE TITLE
Replace the patched `node-sass` when the original library upgrades their `libsass`

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/oui#966]
OUI uses the now deprecated `node-sass`. At the time, `node-sass@8` [inherited a bunch of vulnerabilities](https://security.snyk.io/package/npm/node-sass/8.0.0) from `libsass@3.5.5` and `node-sass@9`, the last release before deprecation. `libsass` is also deprecated and they last release is `libsass@3.6.5` which currently has no known CVEs.

To work around the deprecated `node-sass` not getting any updates, their last version, v9.0.0, was forked patched with `libsass@3.6.5`. [The result](https://github.com/AMoo-Miki/node-sass/tree/v9.0.0-libsass-3.6.5) was released as `@amoo-miki/node-sass@9.0.0-libsass-3.6.5`.

In addition to the newer libsass, the [following changes](https://github.com/AMoo-Miki/node-sass/commit/43c74c0966b05c1e21a1e5e20a0c467ec8e669b4) were introduced:
* Make `quote()` accept non-string values for bwc
* Add minor testing around quotes
* Add Node 14 support
* Automate releases to GitHub
* Bump mocha

If `node-sass` ever updates the version of `libsass` to 3.6.5, after verifying that they would be backward compatible wrt (1) Node 14 and (2) `quote`, the changes in #912 can be removed.

If `libsass` ever makes a new release that we need to have, fork `node-sass@9.0.0` and add `libsass` while being mindful of the changes that are not backward compatible.

**Comment by BSFishy** [comment]
Additionally, for the bump, we needed to upgrade `sass-loader`. We couldn't do a major version bump, as it removes support for Webpack 4. However, `sass-loader@10.4.1` doesn't support `node-sass@9.0.0`. Since nothing has changed in the API of `node-sass` 9, we can add support by forking and updating the semver satisfies query here:

**Comment by AMoo-Miki** [comment]
I would rather drop libsass-based libraries entirely and employ your efforts on dart-embedded.
